# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface1.ui'
#
# Created: Thu Apr  7 11:00:21 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1371, 883)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))

        self.Tab = QtGui.QTabWidget(self.centralwidget)
        self.Tab.setEnabled(True)
        self.Tab.setGeometry(QtCore.QRect(0, 0, 1371, 841))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Tab.setFont(font)
        self.Tab.setMouseTracking(True)
        self.Tab.setTabPosition(QtGui.QTabWidget.North)
        self.Tab.setTabShape(QtGui.QTabWidget.Triangular)
        self.Tab.setUsesScrollButtons(True)
        self.Tab.setDocumentMode(False)
        self.Tab.setTabsClosable(False)
        self.Tab.setMovable(False)
        self.Tab.setObjectName(_fromUtf8("Tab"))
        self.Configuracao = QtGui.QWidget()
        self.Configuracao.setObjectName(_fromUtf8("Configuracao"))
        self.remove = QtGui.QPushButton(self.Configuracao)
        self.remove.setGeometry(QtCore.QRect(640, 330, 81, 41))
        self.remove.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/1351619288_DeleteRed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove.setIcon(icon)
        self.remove.setIconSize(QtCore.QSize(30, 30))
        self.remove.setObjectName(_fromUtf8("remove"))
        self.upload = QtGui.QPushButton(self.Configuracao)
        self.upload.setGeometry(QtCore.QRect(640, 240, 81, 41))
        self.upload.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/Send.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upload.setIcon(icon1)
        self.upload.setIconSize(QtCore.QSize(30, 30))
        self.upload.setObjectName(_fromUtf8("upload"))
        self.groupBox_3 = QtGui.QGroupBox(self.Configuracao)
        self.groupBox_3.setGeometry(QtCore.QRect(730, 90, 631, 511))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 400, 351, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.contador2 = QtGui.QLabel(self.groupBox_2)
        self.contador2.setGeometry(QtCore.QRect(210, 40, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.contador2.setFont(font)
        self.contador2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.contador2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.contador2.setObjectName(_fromUtf8("contador2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(70, 40, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lista_out = QtGui.QTableWidget(self.groupBox_3)
        self.lista_out.setGeometry(QtCore.QRect(60, 70, 531, 301))
        self.lista_out.setToolTip(_fromUtf8(""))
        self.lista_out.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lista_out.setRowCount(1000)
        self.lista_out.setColumnCount(1)
        self.lista_out.setObjectName(_fromUtf8("lista_out"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.lista_out.setHorizontalHeaderItem(0, item)
        self.lista_out.horizontalHeader().setCascadingSectionResizes(True)
        self.lista_out.horizontalHeader().setDefaultSectionSize(500)
        self.lista_out.horizontalHeader().setMinimumSectionSize(27)
        self.lista_out.verticalHeader().setDefaultSectionSize(30)
        self.lista_out.verticalHeader().setMinimumSectionSize(17)
        self.Limpar2 = QtGui.QPushButton(self.groupBox_3)
        self.Limpar2.setGeometry(QtCore.QRect(540, 470, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Limpar2.setFont(font)
        self.Limpar2.setObjectName(_fromUtf8("Limpar2"))
        self.groupBox_4 = QtGui.QGroupBox(self.Configuracao)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 90, 631, 511))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.groupBox = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox.setGeometry(QtCore.QRect(120, 400, 351, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.contador1 = QtGui.QLabel(self.groupBox)
        self.contador1.setGeometry(QtCore.QRect(200, 30, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.contador1.setFont(font)
        self.contador1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.contador1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.contador1.setObjectName(_fromUtf8("contador1"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(100, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lista_in = QtGui.QTableWidget(self.groupBox_4)
        self.lista_in.setGeometry(QtCore.QRect(50, 70, 531, 301))
        self.lista_in.setToolTip(_fromUtf8(""))
        self.lista_in.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lista_in.setRowCount(1000)
        self.lista_in.setColumnCount(1)
        self.lista_in.setObjectName(_fromUtf8("lista_in"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.lista_in.setHorizontalHeaderItem(0, item)
        self.lista_in.horizontalHeader().setVisible(False)
        self.lista_in.horizontalHeader().setCascadingSectionResizes(True)
        self.lista_in.horizontalHeader().setDefaultSectionSize(500)
        self.lista_in.horizontalHeader().setMinimumSectionSize(27)
        self.lista_in.verticalHeader().setDefaultSectionSize(30)
        self.lista_in.verticalHeader().setMinimumSectionSize(17)
        self.Limpar1 = QtGui.QPushButton(self.groupBox_4)
        self.Limpar1.setGeometry(QtCore.QRect(540, 470, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Limpar1.setFont(font)
        self.Limpar1.setObjectName(_fromUtf8("Limpar1"))
        self.LNLS_logo = QtGui.QLabel(self.Configuracao)
        self.LNLS_logo.setGeometry(QtCore.QRect(0, 680, 121, 131))
        self.LNLS_logo.setText(_fromUtf8(""))
        self.LNLS_logo.setPixmap(QtGui.QPixmap(_fromUtf8("imagens/LNLS_sal.jpg")))
        self.LNLS_logo.setScaledContents(True)
        self.LNLS_logo.setObjectName(_fromUtf8("LNLS_logo"))
        self.Analisar = QtGui.QPushButton(self.Configuracao)
        self.Analisar.setEnabled(False)
        self.Analisar.setGeometry(QtCore.QRect(1120, 660, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Analisar.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/Plot.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Analisar.setIcon(icon2)
        self.Analisar.setIconSize(QtCore.QSize(35, 35))
        self.Analisar.setObjectName(_fromUtf8("Analisar"))
        self.progressBar = QtGui.QProgressBar(self.Configuracao)
        self.progressBar.setGeometry(QtCore.QRect(570, 680, 311, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.txtStatus = QtGui.QLineEdit(self.Configuracao)
        self.txtStatus.setGeometry(QtCore.QRect(570, 630, 401, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtStatus.sizePolicy().hasHeightForWidth())
        self.txtStatus.setSizePolicy(sizePolicy)
        self.txtStatus.setToolTip(_fromUtf8("Status"))
        self.txtStatus.setFrame(False)
        self.txtStatus.setReadOnly(True)
        self.txtStatus.setObjectName(_fromUtf8("txtStatus"))
        self.Loading = QtGui.QLabel(self.Configuracao)
        self.Loading.setGeometry(QtCore.QRect(680, 710, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Loading.setFont(font)
        self.Loading.setObjectName(_fromUtf8("Loading"))
        self.label = QtGui.QLabel(self.Configuracao)
        self.label.setGeometry(QtCore.QRect(470, 630, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.Analisededados = QtGui.QLabel(self.Configuracao)
        self.Analisededados.setGeometry(QtCore.QRect(0, 10, 241, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Analisededados.setFont(font)
        self.Analisededados.setObjectName(_fromUtf8("Analisededados"))
        self.line = QtGui.QFrame(self.Configuracao)
        self.line.setGeometry(QtCore.QRect(0, 50, 341, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setLineWidth(2)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.Tab.addTab(self.Configuracao, _fromUtf8(""))
        self.Resultados = QtGui.QWidget()
        self.Resultados.setEnabled(True)
        self.Resultados.setObjectName(_fromUtf8("Resultados"))
        self.tabWidget = QtGui.QTabWidget(self.Resultados)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(270, 10, 1081, 791))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tableWidget = QtGui.QTableWidget(self.tab_3)
        self.tableWidget.setEnabled(False)
        self.tableWidget.setGeometry(QtCore.QRect(70, 500, 931, 251))
        self.tableWidget.setRowCount(144)
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(310, 460, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.graph = matplotlibWidget(self.tab_3)
        self.graph.setGeometry(QtCore.QRect(30, 20, 1011, 431))
        self.graph.setObjectName(_fromUtf8("graph"))
        self.currentview = QtGui.QLineEdit(self.tab_3)
        self.currentview.setGeometry(QtCore.QRect(540, 460, 131, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentview.sizePolicy().hasHeightForWidth())
        self.currentview.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.currentview.setFont(font)
        self.currentview.setToolTip(_fromUtf8("Status"))
        self.currentview.setFrame(False)
        self.currentview.setReadOnly(True)
        self.currentview.setObjectName(_fromUtf8("currentview"))
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(680, 460, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.graph_2 = matplotlibWidget(self.tab)
        self.graph_2.setGeometry(QtCore.QRect(20, 30, 1041, 641))
        self.graph_2.setObjectName(_fromUtf8("graph_2"))
        self.observacao = QtGui.QTextEdit(self.tab)
        self.observacao.setGeometry(QtCore.QRect(310, 680, 371, 71))
        self.observacao.setObjectName(_fromUtf8("observacao"))
        self.label_21 = QtGui.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(190, 700, 101, 21))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.toolBox = QtGui.QToolBox(self.Resultados)
        self.toolBox.setGeometry(QtCore.QRect(0, 30, 261, 781))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.Page = QtGui.QWidget()
        self.Page.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.Page.setObjectName(_fromUtf8("Page"))
        self.groupBox_5 = QtGui.QGroupBox(self.Page)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 10, 261, 271))
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.current = QtGui.QComboBox(self.groupBox_5)
        self.current.setGeometry(QtCore.QRect(120, 70, 121, 20))
        self.current.setObjectName(_fromUtf8("current"))
        self.units = QtGui.QComboBox(self.groupBox_5)
        self.units.setGeometry(QtCore.QRect(100, 130, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.units.setFont(font)
        self.units.setObjectName(_fromUtf8("units"))
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(10, 120, 61, 41))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.plot = QtGui.QPushButton(self.groupBox_5)
        self.plot.setGeometry(QtCore.QRect(190, 220, 61, 31))
        self.plot.setObjectName(_fromUtf8("plot"))
        self.habildata = QtGui.QCheckBox(self.groupBox_5)
        self.habildata.setEnabled(True)
        self.habildata.setGeometry(QtCore.QRect(10, 180, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.habildata.setFont(font)
        self.habildata.setChecked(True)
        self.habildata.setObjectName(_fromUtf8("habildata"))
        self.groupBox_6 = QtGui.QGroupBox(self.Page)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 290, 261, 211))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.units_2 = QtGui.QComboBox(self.groupBox_6)
        self.units_2.setGeometry(QtCore.QRect(90, 70, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.units_2.setFont(font)
        self.units_2.setObjectName(_fromUtf8("units_2"))
        self.label_7 = QtGui.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 61, 41))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.plot_2 = QtGui.QPushButton(self.groupBox_6)
        self.plot_2.setGeometry(QtCore.QRect(190, 170, 61, 31))
        self.plot_2.setObjectName(_fromUtf8("plot_2"))
        self.label_9 = QtGui.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(10, 120, 71, 41))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.average = QtGui.QComboBox(self.groupBox_6)
        self.average.setGeometry(QtCore.QRect(90, 130, 69, 22))
        self.average.setObjectName(_fromUtf8("average"))
        self.average.addItem(_fromUtf8(""))
        self.average.addItem(_fromUtf8(""))
        self.label_15 = QtGui.QLabel(self.Page)
        self.label_15.setGeometry(QtCore.QRect(60, 590, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_12 = QtGui.QLabel(self.Page)
        self.label_12.setGeometry(QtCore.QRect(20, 560, 31, 21))
        self.label_12.setStyleSheet(_fromUtf8("background-color: rgb(221, 221, 221);"))
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_14 = QtGui.QLabel(self.Page)
        self.label_14.setGeometry(QtCore.QRect(60, 560, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_13 = QtGui.QLabel(self.Page)
        self.label_13.setGeometry(QtCore.QRect(20, 590, 31, 21))
        self.label_13.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 255, 0);"))
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.line_4 = QtGui.QFrame(self.Page)
        self.line_4.setGeometry(QtCore.QRect(0, 530, 241, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_16 = QtGui.QLabel(self.Page)
        self.label_16.setGeometry(QtCore.QRect(10, 520, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/flat-icon-bar-graphics-statistics-chart-graph.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.Page, icon3, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.Curvas = QtGui.QPushButton(self.page_2)
        self.Curvas.setGeometry(QtCore.QRect(170, 270, 81, 41))
        self.Curvas.setObjectName(_fromUtf8("Curvas"))
        self.dadosbrutos = QtGui.QPushButton(self.page_2)
        self.dadosbrutos.setGeometry(QtCore.QRect(0, 270, 121, 41))
        self.dadosbrutos.setObjectName(_fromUtf8("dadosbrutos"))
        self.listarq = QtGui.QListWidget(self.page_2)
        self.listarq.setGeometry(QtCore.QRect(0, 10, 261, 251))
        self.listarq.setObjectName(_fromUtf8("listarq"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/chart_xy_graph_statistics-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_2, icon4, _fromUtf8(""))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page.setObjectName(_fromUtf8("page"))
        self.PlotHyst = QtGui.QPushButton(self.page)
        self.PlotHyst.setGeometry(QtCore.QRect(60, 280, 111, 41))
        self.PlotHyst.setObjectName(_fromUtf8("PlotHyst"))
        self.listarq_2 = QtGui.QListWidget(self.page)
        self.listarq_2.setGeometry(QtCore.QRect(0, 0, 261, 251))
        self.listarq_2.setObjectName(_fromUtf8("listarq_2"))
        item = QtGui.QListWidgetItem()
        self.listarq_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listarq_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listarq_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listarq_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listarq_2.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listarq_2.addItem(item)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/Actions-office-chart-line-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page, icon5, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 261, 649))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.salvar = QtGui.QPushButton(self.page_3)
        self.salvar.setGeometry(QtCore.QRect(140, 600, 101, 31))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.salvar.setIcon(icon6)
        self.salvar.setObjectName(_fromUtf8("salvar"))
        self.groupBox_7 = QtGui.QGroupBox(self.page_3)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 0, 261, 171))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.listarq_3 = QtGui.QListWidget(self.groupBox_7)
        self.listarq_3.setGeometry(QtCore.QRect(0, 30, 261, 131))
        self.listarq_3.setObjectName(_fromUtf8("listarq_3"))
        self.groupBox_8 = QtGui.QGroupBox(self.page_3)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 180, 261, 261))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.label_10 = QtGui.QLabel(self.groupBox_8)
        self.label_10.setGeometry(QtCore.QRect(20, 30, 151, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.ambos = QtGui.QRadioButton(self.groupBox_8)
        self.ambos.setGeometry(QtCore.QRect(20, 110, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ambos.setFont(font)
        self.ambos.setObjectName(_fromUtf8("ambos"))
        self.ResiNormal = QtGui.QRadioButton(self.groupBox_8)
        self.ResiNormal.setGeometry(QtCore.QRect(20, 50, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ResiNormal.setFont(font)
        self.ResiNormal.setObjectName(_fromUtf8("ResiNormal"))
        self.ResiSkew = QtGui.QRadioButton(self.groupBox_8)
        self.ResiSkew.setGeometry(QtCore.QRect(20, 80, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ResiSkew.setFont(font)
        self.ResiSkew.setObjectName(_fromUtf8("ResiSkew"))
        self.line_2 = QtGui.QFrame(self.groupBox_8)
        self.line_2.setGeometry(QtCore.QRect(10, 40, 241, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_11 = QtGui.QLabel(self.groupBox_8)
        self.label_11.setGeometry(QtCore.QRect(10, 140, 141, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.line_3 = QtGui.QFrame(self.groupBox_8)
        self.line_3.setGeometry(QtCore.QRect(10, 150, 241, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.ResiSkew_2 = QtGui.QRadioButton(self.groupBox_8)
        self.ResiSkew_2.setGeometry(QtCore.QRect(20, 190, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ResiSkew_2.setFont(font)
        self.ResiSkew_2.setObjectName(_fromUtf8("ResiSkew_2"))
        self.ResiNormal_2 = QtGui.QRadioButton(self.groupBox_8)
        self.ResiNormal_2.setGeometry(QtCore.QRect(20, 160, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ResiNormal_2.setFont(font)
        self.ResiNormal_2.setObjectName(_fromUtf8("ResiNormal_2"))
        self.criar_tabela = QtGui.QPushButton(self.groupBox_8)
        self.criar_tabela.setGeometry(QtCore.QRect(80, 220, 91, 31))
        self.criar_tabela.setObjectName(_fromUtf8("criar_tabela"))
        self.criar_tabela_2 = QtGui.QPushButton(self.page_3)
        self.criar_tabela_2.setGeometry(QtCore.QRect(20, 600, 101, 31))
        self.criar_tabela_2.setObjectName(_fromUtf8("criar_tabela_2"))
        self.groupBox_9 = QtGui.QGroupBox(self.page_3)
        self.groupBox_9.setGeometry(QtCore.QRect(0, 440, 261, 151))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.label_17 = QtGui.QLabel(self.groupBox_9)
        self.label_17.setGeometry(QtCore.QRect(10, 30, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.n_espirasVar = QtGui.QLineEdit(self.groupBox_9)
        self.n_espirasVar.setGeometry(QtCore.QRect(170, 120, 81, 20))
        self.n_espirasVar.setObjectName(_fromUtf8("n_espirasVar"))
        self.label_18 = QtGui.QLabel(self.groupBox_9)
        self.label_18.setGeometry(QtCore.QRect(10, 60, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.CurrVar = QtGui.QLineEdit(self.groupBox_9)
        self.CurrVar.setGeometry(QtCore.QRect(170, 90, 81, 20))
        self.CurrVar.setObjectName(_fromUtf8("CurrVar"))
        self.label_19 = QtGui.QLabel(self.groupBox_9)
        self.label_19.setGeometry(QtCore.QRect(10, 90, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.groupBox_9)
        self.label_20.setGeometry(QtCore.QRect(10, 120, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.IndutVar = QtGui.QLineEdit(self.groupBox_9)
        self.IndutVar.setGeometry(QtCore.QRect(170, 30, 81, 20))
        self.IndutVar.setObjectName(_fromUtf8("IndutVar"))
        self.TensaoVar = QtGui.QLineEdit(self.groupBox_9)
        self.TensaoVar.setGeometry(QtCore.QRect(170, 60, 81, 20))
        self.TensaoVar.setObjectName(_fromUtf8("TensaoVar"))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/table_excel_row_document_teach-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_3, icon7, _fromUtf8(""))
        self.Tab.addTab(self.Resultados, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1371, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.Abrir = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("imagens/7547_128x128.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Abrir.setIcon(icon8)
        self.Abrir.setObjectName(_fromUtf8("Abrir"))
        self.menuFile.addAction(self.Abrir)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.Tab.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(3)
        self.current.setCurrentIndex(-1)
        self.units.setCurrentIndex(-1)
        self.units_2.setCurrentIndex(-1)
        self.average.setCurrentIndex(0)
        self.listarq.setCurrentRow(-1)
        self.listarq_2.setCurrentRow(-1)
        self.listarq_3.setCurrentRow(-1)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.remove.setToolTip(_translate("MainWindow", "<html><head/><body><p>Excluir arquivos da lista de dados selecionados.</p></body></html>", None))
        self.upload.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enviar arquivos para lista de dados selecionados.</p></body></html>", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Lista de dados selecionados", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Número", None))
        self.contador2.setText(_translate("MainWindow", "0000", None))
        self.label_3.setText(_translate("MainWindow", "Selecionado:", None))
        item = self.lista_out.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Arquivo", None))
        self.Limpar2.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Limpar tabela.</span></p></body></html>", None))
        self.Limpar2.setText(_translate("MainWindow", "Limpar", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Lista de entrada dos dados", None))
        self.groupBox.setTitle(_translate("MainWindow", "Número", None))
        self.contador1.setText(_translate("MainWindow", "0000", None))
        self.label_2.setText(_translate("MainWindow", "Total:", None))
        item = self.lista_in.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Arquivo", None))
        self.Limpar1.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Limpar tabela.</span></p></body></html>", None))
        self.Limpar1.setText(_translate("MainWindow", "Limpar", None))
        self.Analisar.setText(_translate("MainWindow", "Analisar", None))
        self.Loading.setText(_translate("MainWindow", "Loading", None))
        self.label.setText(_translate("MainWindow", "Status:", None))
        self.Analisededados.setText(_translate("MainWindow", "Análise de dados", None))
        self.Tab.setTabText(self.Tab.indexOf(self.Configuracao), _translate("MainWindow", "Configuração", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Volta 1", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Volta 2", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Volta 3", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Volta 4", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Volta 5", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Volta 6", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Volta 7", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Volta 8", None))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Volta 9", None))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Volta 10", None))
        self.label_4.setText(_translate("MainWindow", "Dados brutos da curva:", None))
        self.label_8.setText(_translate("MainWindow", "A", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Resultados", None))
        self.label_21.setText(_translate("MainWindow", "Observação:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Gráficos", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Corrente individual", None))
        self.label_5.setText(_translate("MainWindow", "Correntes (A):", None))
        self.label_6.setText(_translate("MainWindow", "Coluna:", None))
        self.plot.setText(_translate("MainWindow", "Plot", None))
        self.habildata.setText(_translate("MainWindow", "Habilitar dados no cursor", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Plotar todas as correntes", None))
        self.label_7.setText(_translate("MainWindow", "Coluna:", None))
        self.plot_2.setText(_translate("MainWindow", "Plot", None))
        self.label_9.setText(_translate("MainWindow", "Média:", None))
        self.average.setItemText(0, _translate("MainWindow", "ON", None))
        self.average.setItemText(1, _translate("MainWindow", "OFF", None))
        self.label_15.setText(_translate("MainWindow", "Correspondem às médias", None))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>Correspondem aos desvios</p></body></html>", None))
        self.label_16.setText(_translate("MainWindow", "Legenda:", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Page), _translate("MainWindow", "Multipolos", None))
        self.Curvas.setText(_translate("MainWindow", "Curvas", None))
        self.dadosbrutos.setText(_translate("MainWindow", "Dados Brutos", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Curvas", None))
        self.PlotHyst.setText(_translate("MainWindow", "Plot", None))
        __sortingEnabled = self.listarq_2.isSortingEnabled()
        self.listarq_2.setSortingEnabled(False)
        item = self.listarq_2.item(0)
        item.setText(_translate("MainWindow", "Dipole (n=1)", None))
        item = self.listarq_2.item(1)
        item.setText(_translate("MainWindow", "Quadrupole (n=2)", None))
        item = self.listarq_2.item(2)
        item.setText(_translate("MainWindow", "Sextupole (n=3)", None))
        item = self.listarq_2.item(3)
        item.setText(_translate("MainWindow", "Octupole (n=4)", None))
        item = self.listarq_2.item(4)
        item.setText(_translate("MainWindow", "Decapole (n=5)", None))
        item = self.listarq_2.item(5)
        item.setText(_translate("MainWindow", "n-pole (n>5)", None))
        self.listarq_2.setSortingEnabled(__sortingEnabled)
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Excitação", None))
        self.salvar.setText(_translate("MainWindow", " Salvar", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Selecionar arquivo", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Modo", None))
        self.label_10.setText(_translate("MainWindow", "Correntes individuais", None))
        self.ambos.setText(_translate("MainWindow", "Ambos", None))
        self.ResiNormal.setText(_translate("MainWindow", "Residual Normal Normalizado", None))
        self.ResiSkew.setText(_translate("MainWindow", "Residual Skew Normalizado", None))
        self.label_11.setText(_translate("MainWindow", "Todas as correntes", None))
        self.ResiSkew_2.setText(_translate("MainWindow", "Residual Skew Normalizado", None))
        self.ResiNormal_2.setText(_translate("MainWindow", "Residual Normal Normalizado", None))
        self.criar_tabela.setText(_translate("MainWindow", "Plotar", None))
        self.criar_tabela_2.setText(_translate("MainWindow", "Criar Tabela", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Ensaios Elétricos", None))
        self.label_17.setText(_translate("MainWindow", "Indutância [mH]:", None))
        self.label_18.setText(_translate("MainWindow", "Tensão [V]:", None))
        self.label_19.setText(_translate("MainWindow", "Corrente Máxima [A]:", None))
        self.label_20.setText(_translate("MainWindow", "Número de Espiras", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Tabelas e Gráficos Residuais", None))
        self.Tab.setTabText(self.Tab.indexOf(self.Resultados), _translate("MainWindow", "Resultados", None))
        self.menuFile.setTitle(_translate("MainWindow", "Arquivo", None))
        self.Abrir.setText(_translate("MainWindow", "Open Files", None))

from PlotGUI import matplotlibWidget
