# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface_rc_analysis.ui'
#
# Created: Mon Dec  5 15:46:12 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1234, 925)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.Tab = QtGui.QTabWidget(self.centralwidget)
        self.Tab.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Tab.setFont(font)
        self.Tab.setMouseTracking(True)
        self.Tab.setTabPosition(QtGui.QTabWidget.North)
        self.Tab.setTabShape(QtGui.QTabWidget.Triangular)
        self.Tab.setUsesScrollButtons(True)
        self.Tab.setDocumentMode(False)
        self.Tab.setTabsClosable(False)
        self.Tab.setMovable(False)
        self.Tab.setObjectName(_fromUtf8("Tab"))
        self.Configuracao = QtGui.QWidget()
        self.Configuracao.setObjectName(_fromUtf8("Configuracao"))
        self.gridLayout_3 = QtGui.QGridLayout(self.Configuracao)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.Configuracao)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.LNLS_logo = QtGui.QLabel(self.groupBox)
        self.LNLS_logo.setGeometry(QtCore.QRect(1110, 10, 70, 80))
        self.LNLS_logo.setText(_fromUtf8(""))
        self.LNLS_logo.setPixmap(QtGui.QPixmap(_fromUtf8(":/Imagens/imagens/LNLS_sal.jpg")))
        self.LNLS_logo.setScaledContents(True)
        self.LNLS_logo.setMargin(1)
        self.LNLS_logo.setObjectName(_fromUtf8("LNLS_logo"))
        self.bt_upload_files = QtGui.QPushButton(self.groupBox)
        self.bt_upload_files.setGeometry(QtCore.QRect(560, 190, 81, 40))
        self.bt_upload_files.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Imagens/imagens/Send.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_upload_files.setIcon(icon)
        self.bt_upload_files.setIconSize(QtCore.QSize(30, 30))
        self.bt_upload_files.setObjectName(_fromUtf8("bt_upload_files"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 70, 540, 740))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_2.setGeometry(QtCore.QRect(60, 30, 350, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.lb_contador_in = QtGui.QLabel(self.groupBox_2)
        self.lb_contador_in.setGeometry(QtCore.QRect(190, 20, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_contador_in.setFont(font)
        self.lb_contador_in.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lb_contador_in.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_contador_in.setObjectName(_fromUtf8("lb_contador_in"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(90, 30, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lista_in = QtGui.QTableWidget(self.groupBox_4)
        self.lista_in.setGeometry(QtCore.QRect(10, 100, 520, 630))
        self.lista_in.setToolTip(_fromUtf8(""))
        self.lista_in.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.lista_in.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.lista_in.setAutoScroll(False)
        self.lista_in.setAutoScrollMargin(150)
        self.lista_in.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lista_in.setTextElideMode(QtCore.Qt.ElideRight)
        self.lista_in.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.lista_in.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.lista_in.setRowCount(0)
        self.lista_in.setColumnCount(1)
        self.lista_in.setObjectName(_fromUtf8("lista_in"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.lista_in.setHorizontalHeaderItem(0, item)
        self.lista_in.horizontalHeader().setVisible(False)
        self.lista_in.horizontalHeader().setCascadingSectionResizes(True)
        self.lista_in.horizontalHeader().setDefaultSectionSize(1000)
        self.lista_in.horizontalHeader().setMinimumSectionSize(27)
        self.lista_in.verticalHeader().setDefaultSectionSize(30)
        self.lista_in.verticalHeader().setMinimumSectionSize(17)
        self.bt_limpar_lista_in = QtGui.QPushButton(self.groupBox_4)
        self.bt_limpar_lista_in.setGeometry(QtCore.QRect(420, 50, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_limpar_lista_in.setFont(font)
        self.bt_limpar_lista_in.setObjectName(_fromUtf8("bt_limpar_lista_in"))
        self.Analisededados = QtGui.QLabel(self.groupBox)
        self.Analisededados.setGeometry(QtCore.QRect(20, 0, 241, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Analisededados.setFont(font)
        self.Analisededados.setObjectName(_fromUtf8("Analisededados"))
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(20, 40, 240, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setLineWidth(2)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(650, 70, 530, 740))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_5.setGeometry(QtCore.QRect(60, 30, 351, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.lb_contador_out = QtGui.QLabel(self.groupBox_5)
        self.lb_contador_out.setGeometry(QtCore.QRect(210, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_contador_out.setFont(font)
        self.lb_contador_out.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lb_contador_out.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_contador_out.setObjectName(_fromUtf8("lb_contador_out"))
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        self.label_3.setGeometry(QtCore.QRect(70, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.bt_limpar_lista_out = QtGui.QPushButton(self.groupBox_3)
        self.bt_limpar_lista_out.setGeometry(QtCore.QRect(420, 50, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_limpar_lista_out.setFont(font)
        self.bt_limpar_lista_out.setObjectName(_fromUtf8("bt_limpar_lista_out"))
        self.lista_out = QtGui.QTableWidget(self.groupBox_3)
        self.lista_out.setGeometry(QtCore.QRect(10, 100, 510, 630))
        self.lista_out.setToolTip(_fromUtf8(""))
        self.lista_out.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.lista_out.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.lista_out.setAutoScroll(False)
        self.lista_out.setAutoScrollMargin(150)
        self.lista_out.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lista_out.setTextElideMode(QtCore.Qt.ElideRight)
        self.lista_out.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.lista_out.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.lista_out.setRowCount(0)
        self.lista_out.setColumnCount(1)
        self.lista_out.setObjectName(_fromUtf8("lista_out"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.lista_out.setHorizontalHeaderItem(0, item)
        self.lista_out.horizontalHeader().setVisible(False)
        self.lista_out.horizontalHeader().setCascadingSectionResizes(True)
        self.lista_out.horizontalHeader().setDefaultSectionSize(1000)
        self.lista_out.horizontalHeader().setMinimumSectionSize(27)
        self.lista_out.verticalHeader().setDefaultSectionSize(30)
        self.lista_out.verticalHeader().setMinimumSectionSize(17)
        self.bt_remove_files = QtGui.QPushButton(self.groupBox)
        self.bt_remove_files.setGeometry(QtCore.QRect(560, 280, 81, 40))
        self.bt_remove_files.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Imagens/imagens/1351619288_DeleteRed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_remove_files.setIcon(icon1)
        self.bt_remove_files.setIconSize(QtCore.QSize(30, 30))
        self.bt_remove_files.setObjectName(_fromUtf8("bt_remove_files"))
        self.bt_analisar_dados = QtGui.QPushButton(self.groupBox)
        self.bt_analisar_dados.setGeometry(QtCore.QRect(650, 10, 160, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bt_analisar_dados.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Imagens/imagens/Plot.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_analisar_dados.setIcon(icon2)
        self.bt_analisar_dados.setIconSize(QtCore.QSize(35, 35))
        self.bt_analisar_dados.setObjectName(_fromUtf8("bt_analisar_dados"))
        self.pb_openfile = QtGui.QPushButton(self.groupBox)
        self.pb_openfile.setGeometry(QtCore.QRect(390, 10, 160, 50))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Imagens/imagens/file_add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_openfile.setIcon(icon3)
        self.pb_openfile.setObjectName(_fromUtf8("pb_openfile"))
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.Tab.addTab(self.Configuracao, _fromUtf8(""))
        self.Multipolos = QtGui.QWidget()
        self.Multipolos.setObjectName(_fromUtf8("Multipolos"))
        self.groupBox_25 = QtGui.QGroupBox(self.Multipolos)
        self.groupBox_25.setGeometry(QtCore.QRect(10, 10, 1200, 820))
        self.groupBox_25.setTitle(_fromUtf8(""))
        self.groupBox_25.setObjectName(_fromUtf8("groupBox_25"))
        self.groupBox_26 = QtGui.QGroupBox(self.groupBox_25)
        self.groupBox_26.setGeometry(QtCore.QRect(280, 10, 310, 150))
        self.groupBox_26.setObjectName(_fromUtf8("groupBox_26"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_26)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_81 = QtGui.QLabel(self.groupBox_26)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.gridLayout_2.addWidget(self.label_81, 0, 0, 1, 1)
        self.cb_media_mutipolos = QtGui.QComboBox(self.groupBox_26)
        self.cb_media_mutipolos.setObjectName(_fromUtf8("cb_media_mutipolos"))
        self.cb_media_mutipolos.addItem(_fromUtf8(""))
        self.cb_media_mutipolos.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cb_media_mutipolos, 1, 1, 1, 1)
        self.cb_nome_coluna2 = QtGui.QComboBox(self.groupBox_26)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_nome_coluna2.setFont(font)
        self.cb_nome_coluna2.setObjectName(_fromUtf8("cb_nome_coluna2"))
        self.gridLayout_2.addWidget(self.cb_nome_coluna2, 0, 1, 1, 2)
        self.label_82 = QtGui.QLabel(self.groupBox_26)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.gridLayout_2.addWidget(self.label_82, 1, 0, 1, 1)
        self.tb_table_2 = QtGui.QToolButton(self.groupBox_26)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/Imagens/imagens/table_excel_row_document_teach-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_table_2.setIcon(icon4)
        self.tb_table_2.setIconSize(QtCore.QSize(40, 20))
        self.tb_table_2.setObjectName(_fromUtf8("tb_table_2"))
        self.gridLayout_2.addWidget(self.tb_table_2, 0, 3, 1, 1)
        self.bt_plot_multipolos_correntes = QtGui.QPushButton(self.groupBox_26)
        self.bt_plot_multipolos_correntes.setObjectName(_fromUtf8("bt_plot_multipolos_correntes"))
        self.gridLayout_2.addWidget(self.bt_plot_multipolos_correntes, 1, 2, 1, 2)
        self.groupBox_27 = QtGui.QGroupBox(self.groupBox_25)
        self.groupBox_27.setGeometry(QtCore.QRect(10, 10, 270, 150))
        self.groupBox_27.setCheckable(False)
        self.groupBox_27.setObjectName(_fromUtf8("groupBox_27"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_27)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cb_nome_coluna = QtGui.QComboBox(self.groupBox_27)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_nome_coluna.setFont(font)
        self.cb_nome_coluna.setObjectName(_fromUtf8("cb_nome_coluna"))
        self.gridLayout.addWidget(self.cb_nome_coluna, 1, 1, 1, 3)
        self.label_84 = QtGui.QLabel(self.groupBox_27)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.gridLayout.addWidget(self.label_84, 1, 0, 1, 1)
        self.label_83 = QtGui.QLabel(self.groupBox_27)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_83.setFont(font)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.gridLayout.addWidget(self.label_83, 0, 0, 1, 2)
        self.cb_corrente = QtGui.QComboBox(self.groupBox_27)
        self.cb_corrente.setObjectName(_fromUtf8("cb_corrente"))
        self.gridLayout.addWidget(self.cb_corrente, 0, 2, 1, 2)
        self.bt_plot_multipolos = QtGui.QPushButton(self.groupBox_27)
        self.bt_plot_multipolos.setObjectName(_fromUtf8("bt_plot_multipolos"))
        self.gridLayout.addWidget(self.bt_plot_multipolos, 2, 1, 1, 3)
        self.tb_table_1 = QtGui.QToolButton(self.groupBox_27)
        self.tb_table_1.setIcon(icon4)
        self.tb_table_1.setIconSize(QtCore.QSize(40, 20))
        self.tb_table_1.setObjectName(_fromUtf8("tb_table_1"))
        self.gridLayout.addWidget(self.tb_table_1, 2, 0, 1, 1)
        self.groupBox_29 = QtGui.QGroupBox(self.groupBox_25)
        self.groupBox_29.setGeometry(QtCore.QRect(840, 10, 350, 150))
        self.groupBox_29.setObjectName(_fromUtf8("groupBox_29"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_29)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_85 = QtGui.QLabel(self.groupBox_29)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_85.setFont(font)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.gridLayout_9.addWidget(self.label_85, 0, 0, 1, 1)
        self.label_86 = QtGui.QLabel(self.groupBox_29)
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.gridLayout_9.addWidget(self.label_86, 1, 0, 1, 1)
        self.bt_plot_dados_brutos_all = QtGui.QPushButton(self.groupBox_29)
        self.bt_plot_dados_brutos_all.setObjectName(_fromUtf8("bt_plot_dados_brutos_all"))
        self.gridLayout_9.addWidget(self.bt_plot_dados_brutos_all, 1, 4, 1, 1)
        self.cb_media_dados_brutos = QtGui.QComboBox(self.groupBox_29)
        self.cb_media_dados_brutos.setObjectName(_fromUtf8("cb_media_dados_brutos"))
        self.cb_media_dados_brutos.addItem(_fromUtf8(""))
        self.cb_media_dados_brutos.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.cb_media_dados_brutos, 1, 1, 1, 2)
        self.bt_plot_dados_brutos = QtGui.QPushButton(self.groupBox_29)
        self.bt_plot_dados_brutos.setObjectName(_fromUtf8("bt_plot_dados_brutos"))
        self.gridLayout_9.addWidget(self.bt_plot_dados_brutos, 0, 4, 1, 1)
        self.tb_table_4 = QtGui.QToolButton(self.groupBox_29)
        self.tb_table_4.setIcon(icon4)
        self.tb_table_4.setIconSize(QtCore.QSize(40, 20))
        self.tb_table_4.setObjectName(_fromUtf8("tb_table_4"))
        self.gridLayout_9.addWidget(self.tb_table_4, 1, 3, 1, 1)
        self.cb_corrente_2 = QtGui.QComboBox(self.groupBox_29)
        self.cb_corrente_2.setObjectName(_fromUtf8("cb_corrente_2"))
        self.gridLayout_9.addWidget(self.cb_corrente_2, 0, 1, 1, 3)
        self.groupBox_30 = QtGui.QGroupBox(self.groupBox_25)
        self.groupBox_30.setGeometry(QtCore.QRect(590, 10, 250, 150))
        self.groupBox_30.setObjectName(_fromUtf8("groupBox_30"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_30)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.cb_harmonico = QtGui.QComboBox(self.groupBox_30)
        self.cb_harmonico.setObjectName(_fromUtf8("cb_harmonico"))
        self.gridLayout_10.addWidget(self.cb_harmonico, 0, 1, 1, 2)
        self.label_87 = QtGui.QLabel(self.groupBox_30)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_87.setFont(font)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.gridLayout_10.addWidget(self.label_87, 0, 0, 1, 1)
        self.rb_norm = QtGui.QRadioButton(self.groupBox_30)
        self.rb_norm.setChecked(True)
        self.rb_norm.setObjectName(_fromUtf8("rb_norm"))
        self.gridLayout_10.addWidget(self.rb_norm, 1, 0, 1, 1)
        self.rb_skew = QtGui.QRadioButton(self.groupBox_30)
        self.rb_skew.setObjectName(_fromUtf8("rb_skew"))
        self.gridLayout_10.addWidget(self.rb_skew, 1, 1, 1, 1)
        self.tb_table_3 = QtGui.QToolButton(self.groupBox_30)
        self.tb_table_3.setIcon(icon4)
        self.tb_table_3.setIconSize(QtCore.QSize(40, 20))
        self.tb_table_3.setObjectName(_fromUtf8("tb_table_3"))
        self.gridLayout_10.addWidget(self.tb_table_3, 1, 2, 1, 1)
        self.bt_plot_histerese = QtGui.QPushButton(self.groupBox_30)
        self.bt_plot_histerese.setObjectName(_fromUtf8("bt_plot_histerese"))
        self.gridLayout_10.addWidget(self.bt_plot_histerese, 3, 0, 1, 3)
        self.wt_multipoles = matplotlibWidget(self.groupBox_25)
        self.wt_multipoles.setGeometry(QtCore.QRect(10, 170, 1180, 640))
        self.wt_multipoles.setObjectName(_fromUtf8("wt_multipoles"))
        self.cb_corrente_nome = QtGui.QComboBox(self.groupBox_25)
        self.cb_corrente_nome.setGeometry(QtCore.QRect(720, 10, 90, 24))
        self.cb_corrente_nome.setObjectName(_fromUtf8("cb_corrente_nome"))
        self.cb_corrente_nome.addItem(_fromUtf8(""))
        self.cb_corrente_nome.addItem(_fromUtf8(""))
        self.Tab.addTab(self.Multipolos, _fromUtf8(""))
        self.Tabelas_e_Residuais = QtGui.QWidget()
        self.Tabelas_e_Residuais.setObjectName(_fromUtf8("Tabelas_e_Residuais"))
        self.groupBox_14 = QtGui.QGroupBox(self.Tabelas_e_Residuais)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 10, 1190, 821))
        self.groupBox_14.setTitle(_fromUtf8(""))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.tabWidget_8 = QtGui.QTabWidget(self.groupBox_14)
        self.tabWidget_8.setEnabled(True)
        self.tabWidget_8.setGeometry(QtCore.QRect(10, 190, 1170, 620))
        self.tabWidget_8.setObjectName(_fromUtf8("tabWidget_8"))
        self.tab_15 = QtGui.QWidget()
        self.tab_15.setObjectName(_fromUtf8("tab_15"))
        self.wt_residual = matplotlibWidget(self.tab_15)
        self.wt_residual.setGeometry(QtCore.QRect(0, 0, 1160, 590))
        self.wt_residual.setObjectName(_fromUtf8("wt_residual"))
        self.tabWidget_8.addTab(self.tab_15, _fromUtf8(""))
        self.tab_16 = QtGui.QWidget()
        self.tab_16.setObjectName(_fromUtf8("tab_16"))
        self.observacao_8 = QtGui.QTextEdit(self.tab_16)
        self.observacao_8.setGeometry(QtCore.QRect(310, 680, 371, 71))
        self.observacao_8.setObjectName(_fromUtf8("observacao_8"))
        self.label_94 = QtGui.QLabel(self.tab_16)
        self.label_94.setGeometry(QtCore.QRect(190, 700, 101, 21))
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.currentview_8 = QtGui.QLineEdit(self.tab_16)
        self.currentview_8.setGeometry(QtCore.QRect(530, 5, 131, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentview_8.sizePolicy().hasHeightForWidth())
        self.currentview_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.currentview_8.setFont(font)
        self.currentview_8.setToolTip(_fromUtf8("Status"))
        self.currentview_8.setFrame(False)
        self.currentview_8.setReadOnly(True)
        self.currentview_8.setObjectName(_fromUtf8("currentview_8"))
        self.label_95 = QtGui.QLabel(self.tab_16)
        self.label_95.setGeometry(QtCore.QRect(300, 5, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_95.setFont(font)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.Resi_tabela = QtGui.QTableWidget(self.tab_16)
        self.Resi_tabela.setEnabled(True)
        self.Resi_tabela.setGeometry(QtCore.QRect(40, 40, 1050, 300))
        self.Resi_tabela.setRowCount(144)
        self.Resi_tabela.setColumnCount(10)
        self.Resi_tabela.setObjectName(_fromUtf8("Resi_tabela"))
        item = QtGui.QTableWidgetItem()
        self.Resi_tabela.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.Resi_tabela.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.Resi_tabela.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.Resi_tabela.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.Resi_tabela.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.Resi_tabela.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.Resi_tabela.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.Resi_tabela.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.Resi_tabela.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.Resi_tabela.setHorizontalHeaderItem(9, item)
        self.label_96 = QtGui.QLabel(self.tab_16)
        self.label_96.setGeometry(QtCore.QRect(670, 5, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_96.setFont(font)
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.tabWidget_8.addTab(self.tab_16, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget_8.addTab(self.tab_2, _fromUtf8(""))
        self.groupBox_31 = QtGui.QGroupBox(self.groupBox_14)
        self.groupBox_31.setGeometry(QtCore.QRect(10, 10, 661, 171))
        self.groupBox_31.setObjectName(_fromUtf8("groupBox_31"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_31)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_31)
        self.groupBox_7.setTitle(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.ds_range_min = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.ds_range_min.setMinimum(-18.0)
        self.ds_range_min.setMaximum(18.0)
        self.ds_range_min.setSingleStep(0.1)
        self.ds_range_min.setProperty("value", -18.0)
        self.ds_range_min.setObjectName(_fromUtf8("ds_range_min"))
        self.gridLayout_6.addWidget(self.ds_range_min, 2, 2, 1, 1)
        self.ds_range_max = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.ds_range_max.setMinimum(-18.0)
        self.ds_range_max.setMaximum(18.0)
        self.ds_range_max.setSingleStep(0.1)
        self.ds_range_max.setProperty("value", 18.0)
        self.ds_range_max.setObjectName(_fromUtf8("ds_range_max"))
        self.gridLayout_6.addWidget(self.ds_range_max, 2, 4, 1, 1)
        self.rb_norm_2 = QtGui.QRadioButton(self.groupBox_7)
        self.rb_norm_2.setChecked(True)
        self.rb_norm_2.setObjectName(_fromUtf8("rb_norm_2"))
        self.gridLayout_6.addWidget(self.rb_norm_2, 1, 2, 1, 1)
        self.label_91 = QtGui.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_91.setFont(font)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.gridLayout_6.addWidget(self.label_91, 2, 0, 1, 1)
        self.label_92 = QtGui.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_92.setFont(font)
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.gridLayout_6.addWidget(self.label_92, 2, 3, 1, 1)
        self.label_93 = QtGui.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_93.setFont(font)
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.gridLayout_6.addWidget(self.label_93, 1, 0, 1, 1)
        self.label_98 = QtGui.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_98.setFont(font)
        self.label_98.setAlignment(QtCore.Qt.AlignCenter)
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.gridLayout_6.addWidget(self.label_98, 2, 5, 1, 1)
        self.label_90 = QtGui.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_90.setFont(font)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.gridLayout_6.addWidget(self.label_90, 4, 0, 1, 2)
        self.cb_harmonico_2 = QtGui.QComboBox(self.groupBox_7)
        self.cb_harmonico_2.setObjectName(_fromUtf8("cb_harmonico_2"))
        self.gridLayout_6.addWidget(self.cb_harmonico_2, 4, 2, 1, 2)
        self.ds_range_step = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.ds_range_step.setDecimals(2)
        self.ds_range_step.setMinimum(0.0)
        self.ds_range_step.setMaximum(5.0)
        self.ds_range_step.setSingleStep(0.1)
        self.ds_range_step.setProperty("value", 0.5)
        self.ds_range_step.setObjectName(_fromUtf8("ds_range_step"))
        self.gridLayout_6.addWidget(self.ds_range_step, 2, 6, 1, 1)
        self.rb_skew_2 = QtGui.QRadioButton(self.groupBox_7)
        self.rb_skew_2.setObjectName(_fromUtf8("rb_skew_2"))
        self.gridLayout_6.addWidget(self.rb_skew_2, 1, 4, 1, 1)
        self.label_88 = QtGui.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_88.setFont(font)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.gridLayout_6.addWidget(self.label_88, 0, 0, 1, 1)
        self.cb_corrente_3 = QtGui.QComboBox(self.groupBox_7)
        self.cb_corrente_3.setObjectName(_fromUtf8("cb_corrente_3"))
        self.gridLayout_6.addWidget(self.cb_corrente_3, 0, 2, 1, 3)
        self.gridLayout_5.addWidget(self.groupBox_7, 0, 0, 3, 1)
        self.cb_media_residuais = QtGui.QComboBox(self.groupBox_31)
        self.cb_media_residuais.setObjectName(_fromUtf8("cb_media_residuais"))
        self.cb_media_residuais.addItem(_fromUtf8(""))
        self.cb_media_residuais.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.cb_media_residuais, 0, 2, 1, 1)
        self.label_89 = QtGui.QLabel(self.groupBox_31)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.gridLayout_5.addWidget(self.label_89, 0, 1, 1, 1)
        self.bt_plot_residuais_corrente = QtGui.QPushButton(self.groupBox_31)
        self.bt_plot_residuais_corrente.setObjectName(_fromUtf8("bt_plot_residuais_corrente"))
        self.gridLayout_5.addWidget(self.bt_plot_residuais_corrente, 1, 1, 1, 3)
        self.tb_table_5 = QtGui.QToolButton(self.groupBox_31)
        self.tb_table_5.setIcon(icon4)
        self.tb_table_5.setIconSize(QtCore.QSize(40, 20))
        self.tb_table_5.setObjectName(_fromUtf8("tb_table_5"))
        self.gridLayout_5.addWidget(self.tb_table_5, 0, 3, 1, 1)
        self.bt_plot_residuais_gerais = QtGui.QPushButton(self.groupBox_31)
        self.bt_plot_residuais_gerais.setObjectName(_fromUtf8("bt_plot_residuais_gerais"))
        self.gridLayout_5.addWidget(self.bt_plot_residuais_gerais, 2, 1, 1, 3)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_14)
        self.groupBox_6.setGeometry(QtCore.QRect(710, 10, 461, 171))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.cb_ima_selec = QtGui.QComboBox(self.groupBox_6)
        self.cb_ima_selec.setGeometry(QtCore.QRect(170, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_ima_selec.setFont(font)
        self.cb_ima_selec.setObjectName(_fromUtf8("cb_ima_selec"))
        self.cb_ima_selec.addItem(_fromUtf8(""))
        self.cb_ima_selec.addItem(_fromUtf8(""))
        self.cb_ima_selec.addItem(_fromUtf8(""))
        self.cb_ima_selec.addItem(_fromUtf8(""))
        self.label = QtGui.QLabel(self.groupBox_6)
        self.label.setGeometry(QtCore.QRect(60, 30, 91, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtGui.QLabel(self.groupBox_6)
        self.label_4.setGeometry(QtCore.QRect(80, 120, 71, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.cb_spec_on = QtGui.QComboBox(self.groupBox_6)
        self.cb_spec_on.setGeometry(QtCore.QRect(170, 120, 61, 31))
        self.cb_spec_on.setObjectName(_fromUtf8("cb_spec_on"))
        self.cb_spec_on.addItem(_fromUtf8(""))
        self.cb_spec_on.addItem(_fromUtf8(""))
        self.label_5 = QtGui.QLabel(self.groupBox_6)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.r_ref_box = QtGui.QLineEdit(self.groupBox_6)
        self.r_ref_box.setGeometry(QtCore.QRect(170, 79, 101, 31))
        self.r_ref_box.setObjectName(_fromUtf8("r_ref_box"))
        self.line_2 = QtGui.QFrame(self.groupBox_6)
        self.line_2.setGeometry(QtCore.QRect(270, 20, 20, 151))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.pb_rnd_pts = QtGui.QPushButton(self.groupBox_6)
        self.pb_rnd_pts.setGeometry(QtCore.QRect(310, 60, 141, 71))
        self.pb_rnd_pts.setCheckable(False)
        self.pb_rnd_pts.setObjectName(_fromUtf8("pb_rnd_pts"))
        self.Tab.addTab(self.Tabelas_e_Residuais, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_24 = QtGui.QGroupBox(self.tab)
        self.groupBox_24.setGeometry(QtCore.QRect(860, 20, 311, 151))
        self.groupBox_24.setObjectName(_fromUtf8("groupBox_24"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_24)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.CurrVar = QtGui.QLineEdit(self.groupBox_24)
        self.CurrVar.setObjectName(_fromUtf8("CurrVar"))
        self.gridLayout_8.addWidget(self.CurrVar, 2, 1, 1, 1)
        self.n_espirasVar = QtGui.QLineEdit(self.groupBox_24)
        self.n_espirasVar.setObjectName(_fromUtf8("n_espirasVar"))
        self.gridLayout_8.addWidget(self.n_espirasVar, 3, 1, 1, 1)
        self.label_72 = QtGui.QLabel(self.groupBox_24)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_72.setFont(font)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout_8.addWidget(self.label_72, 0, 0, 1, 1)
        self.TensaoVar = QtGui.QLineEdit(self.groupBox_24)
        self.TensaoVar.setObjectName(_fromUtf8("TensaoVar"))
        self.gridLayout_8.addWidget(self.TensaoVar, 1, 1, 1, 1)
        self.IndutVar = QtGui.QLineEdit(self.groupBox_24)
        self.IndutVar.setObjectName(_fromUtf8("IndutVar"))
        self.gridLayout_8.addWidget(self.IndutVar, 0, 1, 1, 1)
        self.label_73 = QtGui.QLabel(self.groupBox_24)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_73.setFont(font)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.gridLayout_8.addWidget(self.label_73, 1, 0, 1, 1)
        self.label_74 = QtGui.QLabel(self.groupBox_24)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_74.setFont(font)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.gridLayout_8.addWidget(self.label_74, 2, 0, 1, 1)
        self.label_75 = QtGui.QLabel(self.groupBox_24)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_75.setFont(font)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.gridLayout_8.addWidget(self.label_75, 3, 0, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.tab)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 30, 431, 781))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.pb_preview = QtGui.QPushButton(self.groupBox_8)
        self.pb_preview.setGeometry(QtCore.QRect(130, 700, 131, 41))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("D:/ARQ/Lucas/Analise de dados BGL_(priscila)/imagens/Lupa2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_preview.setIcon(icon5)
        self.pb_preview.setIconSize(QtCore.QSize(25, 25))
        self.pb_preview.setObjectName(_fromUtf8("pb_preview"))
        self.graphicsView = QtGui.QGraphicsView(self.groupBox_8)
        self.graphicsView.setGeometry(QtCore.QRect(30, 40, 371, 631))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.bt_generate_rpt = QtGui.QPushButton(self.tab)
        self.bt_generate_rpt.setGeometry(QtCore.QRect(580, 190, 161, 41))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("D:/ARQ/Lucas/Analise de dados BGL_(priscila)/imagens/engine.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_generate_rpt.setIcon(icon6)
        self.bt_generate_rpt.setIconSize(QtCore.QSize(20, 20))
        self.bt_generate_rpt.setObjectName(_fromUtf8("bt_generate_rpt"))
        self.bt_save_rpt = QtGui.QPushButton(self.tab)
        self.bt_save_rpt.setGeometry(QtCore.QRect(580, 280, 161, 41))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("D:/ARQ/Lucas/Analise de dados BGL_(priscila)/imagens/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_save_rpt.setIcon(icon7)
        self.bt_save_rpt.setIconSize(QtCore.QSize(20, 20))
        self.bt_save_rpt.setObjectName(_fromUtf8("bt_save_rpt"))
        self.pb_open_elecdt = QtGui.QPushButton(self.tab)
        self.pb_open_elecdt.setGeometry(QtCore.QRect(970, 180, 111, 41))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("../../.designer/backup/imagens/7547_128x128.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_open_elecdt.setIcon(icon8)
        self.pb_open_elecdt.setIconSize(QtCore.QSize(25, 25))
        self.pb_open_elecdt.setObjectName(_fromUtf8("pb_open_elecdt"))
        self.observacao = QtGui.QTextEdit(self.tab)
        self.observacao.setGeometry(QtCore.QRect(490, 370, 331, 211))
        self.observacao.setObjectName(_fromUtf8("observacao"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(490, 340, 91, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.line_3 = QtGui.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(833, 10, 20, 811))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(450, 10, 20, 811))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.Tab.addTab(self.tab, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.Tab, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1234, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menu_Abrir = QtGui.QAction(MainWindow)
        self.menu_Abrir.setIcon(icon8)
        self.menu_Abrir.setObjectName(_fromUtf8("menu_Abrir"))
        self.menuFile.addAction(self.menu_Abrir)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.Tab.setCurrentIndex(0)
        self.cb_media_mutipolos.setCurrentIndex(0)
        self.cb_nome_coluna2.setCurrentIndex(-1)
        self.cb_nome_coluna.setCurrentIndex(-1)
        self.cb_corrente.setCurrentIndex(-1)
        self.cb_media_dados_brutos.setCurrentIndex(0)
        self.cb_corrente_2.setCurrentIndex(-1)
        self.cb_harmonico.setCurrentIndex(-1)
        self.tabWidget_8.setCurrentIndex(0)
        self.cb_harmonico_2.setCurrentIndex(-1)
        self.cb_corrente_3.setCurrentIndex(-1)
        self.cb_media_residuais.setCurrentIndex(0)
        self.cb_ima_selec.setCurrentIndex(3)
        self.cb_spec_on.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.bt_upload_files.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enviar arquivos para lista de dados selecionados.</p></body></html>", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Lista de entrada dos dados", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Número", None))
        self.lb_contador_in.setText(_translate("MainWindow", "0", None))
        self.label_2.setText(_translate("MainWindow", "Total:", None))
        item = self.lista_in.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Arquivo", None))
        self.bt_limpar_lista_in.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Limpar tabela.</span></p></body></html>", None))
        self.bt_limpar_lista_in.setText(_translate("MainWindow", "Limpar", None))
        self.Analisededados.setText(_translate("MainWindow", "Análise de dados", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Lista de dados selecionados para análise", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Número", None))
        self.lb_contador_out.setText(_translate("MainWindow", "0", None))
        self.label_3.setText(_translate("MainWindow", "Selecionado:", None))
        self.bt_limpar_lista_out.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Limpar tabela.</span></p></body></html>", None))
        self.bt_limpar_lista_out.setText(_translate("MainWindow", "Limpar", None))
        item = self.lista_out.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Arquivo", None))
        self.bt_remove_files.setToolTip(_translate("MainWindow", "<html><head/><body><p>Excluir arquivos da lista de dados selecionados.</p></body></html>", None))
        self.bt_analisar_dados.setText(_translate("MainWindow", "Analisar", None))
        self.pb_openfile.setText(_translate("MainWindow", "Carregar Arquivos", None))
        self.Tab.setTabText(self.Tab.indexOf(self.Configuracao), _translate("MainWindow", "Configuração", None))
        self.groupBox_26.setTitle(_translate("MainWindow", "Multipolos para todas as correntes", None))
        self.label_81.setText(_translate("MainWindow", "Coluna:", None))
        self.cb_media_mutipolos.setItemText(0, _translate("MainWindow", "ON", None))
        self.cb_media_mutipolos.setItemText(1, _translate("MainWindow", "OFF", None))
        self.label_82.setText(_translate("MainWindow", "Média:", None))
        self.tb_table_2.setText(_translate("MainWindow", "...", None))
        self.bt_plot_multipolos_correntes.setText(_translate("MainWindow", "Gerar Gráfico", None))
        self.groupBox_27.setTitle(_translate("MainWindow", "Multipolos para corrente específica", None))
        self.label_84.setText(_translate("MainWindow", "Coluna:", None))
        self.label_83.setText(_translate("MainWindow", "Correntes (A):", None))
        self.bt_plot_multipolos.setText(_translate("MainWindow", "Gerar Gráfico", None))
        self.tb_table_1.setText(_translate("MainWindow", "...", None))
        self.groupBox_29.setTitle(_translate("MainWindow", "Dados brutos", None))
        self.label_85.setText(_translate("MainWindow", "Correntes (A):", None))
        self.label_86.setText(_translate("MainWindow", "Média:", None))
        self.bt_plot_dados_brutos_all.setText(_translate("MainWindow", "Gráficogeral", None))
        self.cb_media_dados_brutos.setItemText(0, _translate("MainWindow", "ON", None))
        self.cb_media_dados_brutos.setItemText(1, _translate("MainWindow", "OFF", None))
        self.bt_plot_dados_brutos.setText(_translate("MainWindow", "Gráfico\n"
"Individual", None))
        self.tb_table_4.setText(_translate("MainWindow", "...", None))
        self.groupBox_30.setTitle(_translate("MainWindow", "Multipolo vs", None))
        self.label_87.setText(_translate("MainWindow", "Harm:", None))
        self.rb_norm.setText(_translate("MainWindow", "Normal", None))
        self.rb_skew.setText(_translate("MainWindow", "Skew", None))
        self.tb_table_3.setText(_translate("MainWindow", "...", None))
        self.bt_plot_histerese.setText(_translate("MainWindow", "Gerar Gráfico", None))
        self.cb_corrente_nome.setItemText(0, _translate("MainWindow", "Corrente", None))
        self.cb_corrente_nome.setItemText(1, _translate("MainWindow", "Nome", None))
        self.Tab.setTabText(self.Tab.indexOf(self.Multipolos), _translate("MainWindow", "Multipolos e dados brutos", None))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.tab_15), _translate("MainWindow", "Gráficos", None))
        self.label_94.setText(_translate("MainWindow", "Observação:", None))
        self.label_95.setText(_translate("MainWindow", "Dados brutos da curva:", None))
        item = self.Resi_tabela.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Volta 1", None))
        item = self.Resi_tabela.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Volta 2", None))
        item = self.Resi_tabela.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Volta 3", None))
        item = self.Resi_tabela.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Volta 4", None))
        item = self.Resi_tabela.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Volta 5", None))
        item = self.Resi_tabela.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Volta 6", None))
        item = self.Resi_tabela.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Volta 7", None))
        item = self.Resi_tabela.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Volta 8", None))
        item = self.Resi_tabela.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Volta 9", None))
        item = self.Resi_tabela.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Volta 10", None))
        self.label_96.setText(_translate("MainWindow", "A", None))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.tab_16), _translate("MainWindow", "Tabelas", None))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.tab_2), _translate("MainWindow", "Comparar Dados", None))
        self.groupBox_31.setTitle(_translate("MainWindow", "Curva de Multipolos Residual Normalizados", None))
        self.rb_norm_2.setText(_translate("MainWindow", "Normal", None))
        self.label_91.setText(_translate("MainWindow", "Intervalo [mm]: ", None))
        self.label_92.setText(_translate("MainWindow", "à", None))
        self.label_93.setText(_translate("MainWindow", "Componente: ", None))
        self.label_98.setText(_translate("MainWindow", "| passos de: ", None))
        self.label_90.setText(_translate("MainWindow", "Harmônico Principal:", None))
        self.rb_skew_2.setText(_translate("MainWindow", "Skew", None))
        self.label_88.setText(_translate("MainWindow", "Correntes (A):", None))
        self.cb_media_residuais.setItemText(0, _translate("MainWindow", "ON", None))
        self.cb_media_residuais.setItemText(1, _translate("MainWindow", "OFF", None))
        self.label_89.setText(_translate("MainWindow", "Média:", None))
        self.bt_plot_residuais_corrente.setText(_translate("MainWindow", "Gráfico Individual", None))
        self.tb_table_5.setText(_translate("MainWindow", "...", None))
        self.bt_plot_residuais_gerais.setText(_translate("MainWindow", "Gráfico Geral", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Especificações e Tolerâncias", None))
        self.cb_ima_selec.setItemText(0, _translate("MainWindow", "Sem modelo", None))
        self.cb_ima_selec.setItemText(1, _translate("MainWindow", "Dipolo", None))
        self.cb_ima_selec.setItemText(2, _translate("MainWindow", "Quadrupolo", None))
        self.cb_ima_selec.setItemText(3, _translate("MainWindow", "Sextupolo", None))
        self.label.setText(_translate("MainWindow", "Tipo de ímã:", None))
        self.label_4.setText(_translate("MainWindow", "Carregar:", None))
        self.cb_spec_on.setItemText(0, _translate("MainWindow", "ON", None))
        self.cb_spec_on.setItemText(1, _translate("MainWindow", "OFF", None))
        self.label_5.setText(_translate("MainWindow", "@Raio de referência\n"
"                    (mm):", None))
        self.r_ref_box.setText(_translate("MainWindow", "17.5", None))
        self.pb_rnd_pts.setText(_translate("MainWindow", "Carregar pontos  \n"
" arbitrários", None))
        self.Tab.setTabText(self.Tab.indexOf(self.Tabelas_e_Residuais), _translate("MainWindow", "Tabelas e Gráficos Residuais", None))
        self.groupBox_24.setTitle(_translate("MainWindow", "Ensaios Elétricos", None))
        self.label_72.setText(_translate("MainWindow", "Indutância [mH]:", None))
        self.label_73.setText(_translate("MainWindow", "Tensão [V]:", None))
        self.label_74.setText(_translate("MainWindow", "Corrente Máxima [A]:", None))
        self.label_75.setText(_translate("MainWindow", "Número de Espiras", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Preview", None))
        self.pb_preview.setText(_translate("MainWindow", "Preview", None))
        self.bt_generate_rpt.setText(_translate("MainWindow", " Gerar Relatório", None))
        self.bt_save_rpt.setText(_translate("MainWindow", " Salvar Relatório", None))
        self.pb_open_elecdt.setText(_translate("MainWindow", "Abrir", None))
        self.label_6.setText(_translate("MainWindow", "Observação:", None))
        self.Tab.setTabText(self.Tab.indexOf(self.tab), _translate("MainWindow", "Relatório", None))
        self.menuFile.setTitle(_translate("MainWindow", "Arquivo", None))
        self.menu_Abrir.setText(_translate("MainWindow", "Abrir Arquivos", None))

from PlotGUI import matplotlibWidget
import resources_analysis_rc
