# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1234, 949)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.group_box_6 = QtGui.QGroupBox(self.centralwidget)
        self.group_box_6.setObjectName(_fromUtf8("group_box_6"))
        self.directory = QtGui.QLineEdit(self.group_box_6)
        self.directory.setGeometry(QtCore.QRect(120, 0, 1091, 27))
        self.directory.setReadOnly(True)
        self.directory.setObjectName(_fromUtf8("directory"))
        self.gridLayout_4.addWidget(self.group_box_6, 1, 0, 1, 1)
        self.main_tab = QtGui.QTabWidget(self.centralwidget)
        self.main_tab.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.main_tab.setFont(font)
        self.main_tab.setMouseTracking(True)
        self.main_tab.setTabPosition(QtGui.QTabWidget.North)
        self.main_tab.setTabShape(QtGui.QTabWidget.Triangular)
        self.main_tab.setUsesScrollButtons(True)
        self.main_tab.setDocumentMode(False)
        self.main_tab.setTabsClosable(False)
        self.main_tab.setMovable(False)
        self.main_tab.setObjectName(_fromUtf8("main_tab"))
        self.configuration = QtGui.QWidget()
        self.configuration.setObjectName(_fromUtf8("configuration"))
        self.gridLayout_3 = QtGui.QGridLayout(self.configuration)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.group_box_1 = QtGui.QGroupBox(self.configuration)
        self.group_box_1.setTitle(_fromUtf8(""))
        self.group_box_1.setObjectName(_fromUtf8("group_box_1"))
        self.lnls_logo = QtGui.QLabel(self.group_box_1)
        self.lnls_logo.setGeometry(QtCore.QRect(1110, 10, 70, 80))
        self.lnls_logo.setText(_fromUtf8(""))
        self.lnls_logo.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/LNLS.jpg")))
        self.lnls_logo.setScaledContents(True)
        self.lnls_logo.setObjectName(_fromUtf8("lnls_logo"))
        self.bt_upload_files = QtGui.QPushButton(self.group_box_1)
        self.bt_upload_files.setGeometry(QtCore.QRect(560, 190, 81, 40))
        self.bt_upload_files.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/send.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_upload_files.setIcon(icon)
        self.bt_upload_files.setIconSize(QtCore.QSize(30, 30))
        self.bt_upload_files.setObjectName(_fromUtf8("bt_upload_files"))
        self.group_box_2 = QtGui.QGroupBox(self.group_box_1)
        self.group_box_2.setGeometry(QtCore.QRect(10, 70, 540, 740))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.group_box_2.setFont(font)
        self.group_box_2.setObjectName(_fromUtf8("group_box_2"))
        self.group_box_3 = QtGui.QGroupBox(self.group_box_2)
        self.group_box_3.setGeometry(QtCore.QRect(60, 30, 350, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.group_box_3.setFont(font)
        self.group_box_3.setObjectName(_fromUtf8("group_box_3"))
        self.input_count = QtGui.QLabel(self.group_box_3)
        self.input_count.setGeometry(QtCore.QRect(190, 20, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.input_count.setFont(font)
        self.input_count.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_count.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.input_count.setObjectName(_fromUtf8("input_count"))
        self.input_count_label = QtGui.QLabel(self.group_box_3)
        self.input_count_label.setGeometry(QtCore.QRect(90, 30, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_count_label.setFont(font)
        self.input_count_label.setObjectName(_fromUtf8("input_count_label"))
        self.input_list = QtGui.QTableWidget(self.group_box_2)
        self.input_list.setGeometry(QtCore.QRect(10, 100, 520, 621))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.input_list.setFont(font)
        self.input_list.setToolTip(_fromUtf8(""))
        self.input_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.input_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.input_list.setAutoScroll(False)
        self.input_list.setAutoScrollMargin(150)
        self.input_list.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.input_list.setTextElideMode(QtCore.Qt.ElideRight)
        self.input_list.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.input_list.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.input_list.setRowCount(0)
        self.input_list.setColumnCount(1)
        self.input_list.setObjectName(_fromUtf8("input_list"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.input_list.setHorizontalHeaderItem(0, item)
        self.input_list.horizontalHeader().setVisible(False)
        self.input_list.horizontalHeader().setCascadingSectionResizes(True)
        self.input_list.horizontalHeader().setDefaultSectionSize(1000)
        self.input_list.horizontalHeader().setMinimumSectionSize(27)
        self.input_list.verticalHeader().setDefaultSectionSize(30)
        self.input_list.verticalHeader().setMinimumSectionSize(17)
        self.bt_clear_input_list = QtGui.QPushButton(self.group_box_2)
        self.bt_clear_input_list.setGeometry(QtCore.QRect(420, 50, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_clear_input_list.setFont(font)
        self.bt_clear_input_list.setObjectName(_fromUtf8("bt_clear_input_list"))
        self.data_analysis_label = QtGui.QLabel(self.group_box_1)
        self.data_analysis_label.setGeometry(QtCore.QRect(20, 0, 321, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.data_analysis_label.setFont(font)
        self.data_analysis_label.setObjectName(_fromUtf8("data_analysis_label"))
        self.line = QtGui.QFrame(self.group_box_1)
        self.line.setGeometry(QtCore.QRect(20, 40, 321, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("3ds"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setLineWidth(2)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.group_box_4 = QtGui.QGroupBox(self.group_box_1)
        self.group_box_4.setGeometry(QtCore.QRect(650, 70, 530, 761))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.group_box_4.setFont(font)
        self.group_box_4.setObjectName(_fromUtf8("group_box_4"))
        self.group_box_5 = QtGui.QGroupBox(self.group_box_4)
        self.group_box_5.setGeometry(QtCore.QRect(60, 30, 351, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.group_box_5.setFont(font)
        self.group_box_5.setObjectName(_fromUtf8("group_box_5"))
        self.output_count = QtGui.QLabel(self.group_box_5)
        self.output_count.setGeometry(QtCore.QRect(210, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.output_count.setFont(font)
        self.output_count.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.output_count.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output_count.setObjectName(_fromUtf8("output_count"))
        self.output_count_label = QtGui.QLabel(self.group_box_5)
        self.output_count_label.setGeometry(QtCore.QRect(70, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.output_count_label.setFont(font)
        self.output_count_label.setObjectName(_fromUtf8("output_count_label"))
        self.bt_clear_output_list = QtGui.QPushButton(self.group_box_4)
        self.bt_clear_output_list.setGeometry(QtCore.QRect(420, 50, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_clear_output_list.setFont(font)
        self.bt_clear_output_list.setObjectName(_fromUtf8("bt_clear_output_list"))
        self.output_list = QtGui.QTableWidget(self.group_box_4)
        self.output_list.setGeometry(QtCore.QRect(10, 100, 510, 621))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.output_list.setFont(font)
        self.output_list.setToolTip(_fromUtf8(""))
        self.output_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.output_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.output_list.setAutoScroll(False)
        self.output_list.setAutoScrollMargin(150)
        self.output_list.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.output_list.setTextElideMode(QtCore.Qt.ElideRight)
        self.output_list.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.output_list.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.output_list.setRowCount(0)
        self.output_list.setColumnCount(1)
        self.output_list.setObjectName(_fromUtf8("output_list"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.output_list.setHorizontalHeaderItem(0, item)
        self.output_list.horizontalHeader().setVisible(False)
        self.output_list.horizontalHeader().setCascadingSectionResizes(True)
        self.output_list.horizontalHeader().setDefaultSectionSize(1000)
        self.output_list.horizontalHeader().setMinimumSectionSize(27)
        self.output_list.verticalHeader().setDefaultSectionSize(30)
        self.output_list.verticalHeader().setMinimumSectionSize(17)
        self.bt_remove_files = QtGui.QPushButton(self.group_box_1)
        self.bt_remove_files.setGeometry(QtCore.QRect(560, 280, 81, 40))
        self.bt_remove_files.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_remove_files.setIcon(icon1)
        self.bt_remove_files.setIconSize(QtCore.QSize(30, 30))
        self.bt_remove_files.setObjectName(_fromUtf8("bt_remove_files"))
        self.bt_data_analysis = QtGui.QPushButton(self.group_box_1)
        self.bt_data_analysis.setGeometry(QtCore.QRect(650, 10, 160, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bt_data_analysis.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/plot.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_data_analysis.setIcon(icon2)
        self.bt_data_analysis.setIconSize(QtCore.QSize(35, 35))
        self.bt_data_analysis.setObjectName(_fromUtf8("bt_data_analysis"))
        self.bt_open_file = QtGui.QPushButton(self.group_box_1)
        self.bt_open_file.setGeometry(QtCore.QRect(390, 10, 160, 50))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/file_add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_open_file.setIcon(icon3)
        self.bt_open_file.setObjectName(_fromUtf8("bt_open_file"))
        self.gridLayout_3.addWidget(self.group_box_1, 0, 0, 1, 1)
        self.main_tab.addTab(self.configuration, _fromUtf8(""))
        self.multipoles = QtGui.QWidget()
        self.multipoles.setObjectName(_fromUtf8("multipoles"))
        self.group_box_7 = QtGui.QGroupBox(self.multipoles)
        self.group_box_7.setGeometry(QtCore.QRect(10, 10, 1200, 820))
        self.group_box_7.setTitle(_fromUtf8(""))
        self.group_box_7.setObjectName(_fromUtf8("group_box_7"))
        self.group_box_9 = QtGui.QGroupBox(self.group_box_7)
        self.group_box_9.setGeometry(QtCore.QRect(290, 9, 261, 151))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.group_box_9.setFont(font)
        self.group_box_9.setObjectName(_fromUtf8("group_box_9"))
        self.gridLayout_2 = QtGui.QGridLayout(self.group_box_9)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.column_label_2 = QtGui.QLabel(self.group_box_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.column_label_2.setFont(font)
        self.column_label_2.setObjectName(_fromUtf8("column_label_2"))
        self.gridLayout_2.addWidget(self.column_label_2, 0, 0, 1, 1)
        self.cb_multipoles_2 = QtGui.QComboBox(self.group_box_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_multipoles_2.setFont(font)
        self.cb_multipoles_2.setObjectName(_fromUtf8("cb_multipoles_2"))
        self.gridLayout_2.addWidget(self.cb_multipoles_2, 0, 1, 1, 3)
        self.avg_label_1 = QtGui.QLabel(self.group_box_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.avg_label_1.setFont(font)
        self.avg_label_1.setObjectName(_fromUtf8("avg_label_1"))
        self.gridLayout_2.addWidget(self.avg_label_1, 1, 0, 1, 1)
        self.bt_table_2 = QtGui.QToolButton(self.group_box_9)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/table.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_table_2.setIcon(icon4)
        self.bt_table_2.setIconSize(QtCore.QSize(40, 20))
        self.bt_table_2.setObjectName(_fromUtf8("bt_table_2"))
        self.gridLayout_2.addWidget(self.bt_table_2, 1, 3, 1, 1)
        self.cb_avg_1 = QtGui.QComboBox(self.group_box_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cb_avg_1.setFont(font)
        self.cb_avg_1.setObjectName(_fromUtf8("cb_avg_1"))
        self.cb_avg_1.addItem(_fromUtf8(""))
        self.cb_avg_1.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cb_avg_1, 1, 1, 1, 2)
        self.bt_plot_multipoles_all = QtGui.QPushButton(self.group_box_9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bt_plot_multipoles_all.setFont(font)
        self.bt_plot_multipoles_all.setObjectName(_fromUtf8("bt_plot_multipoles_all"))
        self.gridLayout_2.addWidget(self.bt_plot_multipoles_all, 2, 0, 1, 4)
        self.group_box_8 = QtGui.QGroupBox(self.group_box_7)
        self.group_box_8.setGeometry(QtCore.QRect(0, 10, 281, 150))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.group_box_8.setFont(font)
        self.group_box_8.setCheckable(False)
        self.group_box_8.setObjectName(_fromUtf8("group_box_8"))
        self.gridLayout = QtGui.QGridLayout(self.group_box_8)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.file_label_1 = QtGui.QLabel(self.group_box_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.file_label_1.setFont(font)
        self.file_label_1.setObjectName(_fromUtf8("file_label_1"))
        self.gridLayout.addWidget(self.file_label_1, 0, 0, 1, 2)
        self.cb_multipoles_1 = QtGui.QComboBox(self.group_box_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_multipoles_1.setFont(font)
        self.cb_multipoles_1.setObjectName(_fromUtf8("cb_multipoles_1"))
        self.gridLayout.addWidget(self.cb_multipoles_1, 1, 1, 1, 3)
        self.column_label_1 = QtGui.QLabel(self.group_box_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.column_label_1.setFont(font)
        self.column_label_1.setObjectName(_fromUtf8("column_label_1"))
        self.gridLayout.addWidget(self.column_label_1, 1, 0, 1, 1)
        self.cb_files_1 = QtGui.QComboBox(self.group_box_8)
        self.cb_files_1.setObjectName(_fromUtf8("cb_files_1"))
        self.gridLayout.addWidget(self.cb_files_1, 0, 2, 1, 2)
        self.bt_table_1 = QtGui.QToolButton(self.group_box_8)
        self.bt_table_1.setIcon(icon4)
        self.bt_table_1.setIconSize(QtCore.QSize(40, 20))
        self.bt_table_1.setObjectName(_fromUtf8("bt_table_1"))
        self.gridLayout.addWidget(self.bt_table_1, 2, 3, 1, 1)
        self.bt_plot_multipoles = QtGui.QPushButton(self.group_box_8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bt_plot_multipoles.setFont(font)
        self.bt_plot_multipoles.setObjectName(_fromUtf8("bt_plot_multipoles"))
        self.gridLayout.addWidget(self.bt_plot_multipoles, 2, 0, 1, 3)
        self.group_box_11 = QtGui.QGroupBox(self.group_box_7)
        self.group_box_11.setGeometry(QtCore.QRect(850, 10, 331, 150))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.group_box_11.setFont(font)
        self.group_box_11.setObjectName(_fromUtf8("group_box_11"))
        self.gridLayout_9 = QtGui.QGridLayout(self.group_box_11)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.cb_files_2 = QtGui.QComboBox(self.group_box_11)
        self.cb_files_2.setObjectName(_fromUtf8("cb_files_2"))
        self.gridLayout_9.addWidget(self.cb_files_2, 0, 2, 1, 3)
        self.file_label_2 = QtGui.QLabel(self.group_box_11)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.file_label_2.setFont(font)
        self.file_label_2.setObjectName(_fromUtf8("file_label_2"))
        self.gridLayout_9.addWidget(self.file_label_2, 0, 0, 1, 2)
        self.bt_plot_raw_data = QtGui.QPushButton(self.group_box_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bt_plot_raw_data.setFont(font)
        self.bt_plot_raw_data.setObjectName(_fromUtf8("bt_plot_raw_data"))
        self.gridLayout_9.addWidget(self.bt_plot_raw_data, 2, 2, 1, 3)
        self.avg_label_2 = QtGui.QLabel(self.group_box_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.avg_label_2.setFont(font)
        self.avg_label_2.setObjectName(_fromUtf8("avg_label_2"))
        self.gridLayout_9.addWidget(self.avg_label_2, 3, 0, 1, 1)
        self.cb_avg_2 = QtGui.QComboBox(self.group_box_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cb_avg_2.setFont(font)
        self.cb_avg_2.setObjectName(_fromUtf8("cb_avg_2"))
        self.cb_avg_2.addItem(_fromUtf8(""))
        self.cb_avg_2.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.cb_avg_2, 3, 1, 1, 1)
        self.bt_plot_raw_data_all = QtGui.QPushButton(self.group_box_11)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.bt_plot_raw_data_all.setFont(font)
        self.bt_plot_raw_data_all.setObjectName(_fromUtf8("bt_plot_raw_data_all"))
        self.gridLayout_9.addWidget(self.bt_plot_raw_data_all, 3, 2, 1, 3)
        self.bt_table_4 = QtGui.QToolButton(self.group_box_11)
        self.bt_table_4.setIcon(icon4)
        self.bt_table_4.setIconSize(QtCore.QSize(40, 20))
        self.bt_table_4.setObjectName(_fromUtf8("bt_table_4"))
        self.gridLayout_9.addWidget(self.bt_table_4, 2, 1, 1, 1)
        self.group_box_10 = QtGui.QGroupBox(self.group_box_7)
        self.group_box_10.setGeometry(QtCore.QRect(570, 10, 261, 151))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.group_box_10.setFont(font)
        self.group_box_10.setObjectName(_fromUtf8("group_box_10"))
        self.gridLayout_10 = QtGui.QGridLayout(self.group_box_10)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.cb_harmonic = QtGui.QComboBox(self.group_box_10)
        self.cb_harmonic.setObjectName(_fromUtf8("cb_harmonic"))
        self.gridLayout_10.addWidget(self.cb_harmonic, 2, 1, 1, 2)
        self.rb_norm = QtGui.QRadioButton(self.group_box_10)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rb_norm.setFont(font)
        self.rb_norm.setChecked(True)
        self.rb_norm.setObjectName(_fromUtf8("rb_norm"))
        self.gridLayout_10.addWidget(self.rb_norm, 5, 0, 1, 1)
        self.rb_skew = QtGui.QRadioButton(self.group_box_10)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rb_skew.setFont(font)
        self.rb_skew.setObjectName(_fromUtf8("rb_skew"))
        self.gridLayout_10.addWidget(self.rb_skew, 5, 1, 1, 1)
        self.bt_table_3 = QtGui.QToolButton(self.group_box_10)
        self.bt_table_3.setIcon(icon4)
        self.bt_table_3.setIconSize(QtCore.QSize(40, 20))
        self.bt_table_3.setObjectName(_fromUtf8("bt_table_3"))
        self.gridLayout_10.addWidget(self.bt_table_3, 5, 2, 1, 1)
        self.bt_plot_hysteresis = QtGui.QPushButton(self.group_box_10)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bt_plot_hysteresis.setFont(font)
        self.bt_plot_hysteresis.setObjectName(_fromUtf8("bt_plot_hysteresis"))
        self.gridLayout_10.addWidget(self.bt_plot_hysteresis, 7, 0, 1, 3)
        self.harmonic_label = QtGui.QLabel(self.group_box_10)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.harmonic_label.setFont(font)
        self.harmonic_label.setObjectName(_fromUtf8("harmonic_label"))
        self.gridLayout_10.addWidget(self.harmonic_label, 2, 0, 1, 1)
        self.cb_hyst_axis_label = QtGui.QComboBox(self.group_box_10)
        self.cb_hyst_axis_label.setObjectName(_fromUtf8("cb_hyst_axis_label"))
        self.gridLayout_10.addWidget(self.cb_hyst_axis_label, 0, 1, 1, 2)
        self.hyst_axis_label_label = QtGui.QLabel(self.group_box_10)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.hyst_axis_label_label.setFont(font)
        self.hyst_axis_label_label.setObjectName(_fromUtf8("hyst_axis_label_label"))
        self.gridLayout_10.addWidget(self.hyst_axis_label_label, 0, 0, 1, 1)
        self.wt_multipoles = matplotlibWidget(self.group_box_7)
        self.wt_multipoles.setGeometry(QtCore.QRect(10, 170, 1180, 640))
        self.wt_multipoles.setObjectName(_fromUtf8("wt_multipoles"))
        self.cb_hyst_axis = QtGui.QComboBox(self.group_box_7)
        self.cb_hyst_axis.setGeometry(QtCore.QRect(679, 10, 141, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_hyst_axis.setFont(font)
        self.cb_hyst_axis.setObjectName(_fromUtf8("cb_hyst_axis"))
        self.main_tab.addTab(self.multipoles, _fromUtf8(""))
        self.residual = QtGui.QWidget()
        self.residual.setObjectName(_fromUtf8("residual"))
        self.group_box_12 = QtGui.QGroupBox(self.residual)
        self.group_box_12.setGeometry(QtCore.QRect(10, 10, 1190, 821))
        self.group_box_12.setTitle(_fromUtf8(""))
        self.group_box_12.setObjectName(_fromUtf8("group_box_12"))
        self.tab_residual = QtGui.QTabWidget(self.group_box_12)
        self.tab_residual.setEnabled(True)
        self.tab_residual.setGeometry(QtCore.QRect(10, 149, 1170, 661))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tab_residual.setFont(font)
        self.tab_residual.setObjectName(_fromUtf8("tab_residual"))
        self.residual_field = QtGui.QWidget()
        self.residual_field.setObjectName(_fromUtf8("residual_field"))
        self.wt_residual = matplotlibWidget(self.residual_field)
        self.wt_residual.setGeometry(QtCore.QRect(0, 0, 1160, 621))
        self.wt_residual.setObjectName(_fromUtf8("wt_residual"))
        self.tab_residual.addTab(self.residual_field, _fromUtf8(""))
        self.residual_multipoles = QtGui.QWidget()
        self.residual_multipoles.setObjectName(_fromUtf8("residual_multipoles"))
        self.wt_residual_comp = matplotlibWidget(self.residual_multipoles)
        self.wt_residual_comp.setGeometry(QtCore.QRect(0, 0, 1161, 621))
        self.wt_residual_comp.setObjectName(_fromUtf8("wt_residual_comp"))
        self.tab_residual.addTab(self.residual_multipoles, _fromUtf8(""))
        self.residual_tables = QtGui.QWidget()
        self.residual_tables.setObjectName(_fromUtf8("residual_tables"))
        self.table_one_file = QtGui.QTableWidget(self.residual_tables)
        self.table_one_file.setEnabled(True)
        self.table_one_file.setGeometry(QtCore.QRect(100, 100, 400, 117))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_one_file.sizePolicy().hasHeightForWidth())
        self.table_one_file.setSizePolicy(sizePolicy)
        self.table_one_file.setMinimumSize(QtCore.QSize(400, 117))
        self.table_one_file.setMaximumSize(QtCore.QSize(600, 117))
        self.table_one_file.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.table_one_file.setAutoFillBackground(False)
        self.table_one_file.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_one_file.setAutoScroll(True)
        self.table_one_file.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table_one_file.setObjectName(_fromUtf8("table_one_file"))
        self.table_one_file.setColumnCount(1)
        self.table_one_file.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.table_one_file.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_one_file.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_one_file.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_one_file.setHorizontalHeaderItem(0, item)
        self.table_one_file.horizontalHeader().setCascadingSectionResizes(False)
        self.table_one_file.horizontalHeader().setDefaultSectionSize(100)
        self.table_one_file.horizontalHeader().setMinimumSectionSize(80)
        self.table_one_file.horizontalHeader().setStretchLastSection(True)
        self.table_avg = QtGui.QTableWidget(self.residual_tables)
        self.table_avg.setEnabled(True)
        self.table_avg.setGeometry(QtCore.QRect(660, 100, 400, 117))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_avg.sizePolicy().hasHeightForWidth())
        self.table_avg.setSizePolicy(sizePolicy)
        self.table_avg.setMinimumSize(QtCore.QSize(400, 117))
        self.table_avg.setMaximumSize(QtCore.QSize(600, 117))
        self.table_avg.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.table_avg.setAutoFillBackground(False)
        self.table_avg.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_avg.setAutoScroll(True)
        self.table_avg.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table_avg.setObjectName(_fromUtf8("table_avg"))
        self.table_avg.setColumnCount(1)
        self.table_avg.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.table_avg.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_avg.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_avg.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_avg.setHorizontalHeaderItem(0, item)
        self.table_avg.horizontalHeader().setCascadingSectionResizes(False)
        self.table_avg.horizontalHeader().setDefaultSectionSize(100)
        self.table_avg.horizontalHeader().setMinimumSectionSize(80)
        self.table_avg.horizontalHeader().setStretchLastSection(True)
        self.table_all_files = QtGui.QTableWidget(self.residual_tables)
        self.table_all_files.setEnabled(True)
        self.table_all_files.setGeometry(QtCore.QRect(30, 340, 1100, 130))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_all_files.sizePolicy().hasHeightForWidth())
        self.table_all_files.setSizePolicy(sizePolicy)
        self.table_all_files.setMinimumSize(QtCore.QSize(400, 130))
        self.table_all_files.setMaximumSize(QtCore.QSize(1100, 117))
        self.table_all_files.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.table_all_files.setAutoFillBackground(False)
        self.table_all_files.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_all_files.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_all_files.setAutoScroll(True)
        self.table_all_files.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.table_all_files.setObjectName(_fromUtf8("table_all_files"))
        self.table_all_files.setColumnCount(1)
        self.table_all_files.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.table_all_files.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_all_files.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_all_files.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_all_files.setHorizontalHeaderItem(0, item)
        self.table_all_files.horizontalHeader().setCascadingSectionResizes(False)
        self.table_all_files.horizontalHeader().setDefaultSectionSize(100)
        self.table_all_files.horizontalHeader().setMinimumSectionSize(80)
        self.table_all_files.horizontalHeader().setStretchLastSection(True)
        self.selected_file_label = QtGui.QLabel(self.residual_tables)
        self.selected_file_label.setGeometry(QtCore.QRect(110, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.selected_file_label.setFont(font)
        self.selected_file_label.setObjectName(_fromUtf8("selected_file_label"))
        self.mean_label = QtGui.QLabel(self.residual_tables)
        self.mean_label.setGeometry(QtCore.QRect(670, 60, 111, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.mean_label.setFont(font)
        self.mean_label.setObjectName(_fromUtf8("mean_label"))
        self.all_files_label = QtGui.QLabel(self.residual_tables)
        self.all_files_label.setGeometry(QtCore.QRect(40, 300, 111, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.all_files_label.setFont(font)
        self.all_files_label.setObjectName(_fromUtf8("all_files_label"))
        self.tab_residual.addTab(self.residual_tables, _fromUtf8(""))
        self.group_box_14 = QtGui.QGroupBox(self.group_box_12)
        self.group_box_14.setGeometry(QtCore.QRect(530, 0, 191, 151))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.group_box_14.setFont(font)
        self.group_box_14.setTitle(_fromUtf8(""))
        self.group_box_14.setObjectName(_fromUtf8("group_box_14"))
        self.gridLayout_5 = QtGui.QGridLayout(self.group_box_14)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.avg_label_3 = QtGui.QLabel(self.group_box_14)
        self.avg_label_3.setObjectName(_fromUtf8("avg_label_3"))
        self.gridLayout_5.addWidget(self.avg_label_3, 1, 0, 1, 1)
        self.bt_plot_residual_field_all = QtGui.QPushButton(self.group_box_14)
        self.bt_plot_residual_field_all.setObjectName(_fromUtf8("bt_plot_residual_field_all"))
        self.gridLayout_5.addWidget(self.bt_plot_residual_field_all, 3, 0, 1, 3)
        self.cb_avg_3 = QtGui.QComboBox(self.group_box_14)
        self.cb_avg_3.setObjectName(_fromUtf8("cb_avg_3"))
        self.cb_avg_3.addItem(_fromUtf8(""))
        self.cb_avg_3.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.cb_avg_3, 1, 1, 1, 1)
        self.bt_table_5 = QtGui.QToolButton(self.group_box_14)
        self.bt_table_5.setIcon(icon4)
        self.bt_table_5.setIconSize(QtCore.QSize(40, 20))
        self.bt_table_5.setObjectName(_fromUtf8("bt_table_5"))
        self.gridLayout_5.addWidget(self.bt_table_5, 1, 2, 1, 1)
        self.bt_plot_residual_field = QtGui.QPushButton(self.group_box_14)
        self.bt_plot_residual_field.setObjectName(_fromUtf8("bt_plot_residual_field"))
        self.gridLayout_5.addWidget(self.bt_plot_residual_field, 0, 0, 1, 3)
        self.group_box_13 = QtGui.QGroupBox(self.group_box_12)
        self.group_box_13.setGeometry(QtCore.QRect(30, 10, 441, 141))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.group_box_13.setFont(font)
        self.group_box_13.setObjectName(_fromUtf8("group_box_13"))
        self.gridLayout_6 = QtGui.QGridLayout(self.group_box_13)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.ds_range_min = QtGui.QDoubleSpinBox(self.group_box_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ds_range_min.setFont(font)
        self.ds_range_min.setPrefix(_fromUtf8(""))
        self.ds_range_min.setDecimals(1)
        self.ds_range_min.setMinimum(-18.0)
        self.ds_range_min.setMaximum(18.0)
        self.ds_range_min.setSingleStep(0.1)
        self.ds_range_min.setProperty("value", -18.0)
        self.ds_range_min.setObjectName(_fromUtf8("ds_range_min"))
        self.gridLayout_6.addWidget(self.ds_range_min, 4, 2, 1, 1)
        self.ds_range_max = QtGui.QDoubleSpinBox(self.group_box_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ds_range_max.setFont(font)
        self.ds_range_max.setDecimals(1)
        self.ds_range_max.setMinimum(-18.0)
        self.ds_range_max.setMaximum(18.0)
        self.ds_range_max.setSingleStep(0.1)
        self.ds_range_max.setProperty("value", 18.0)
        self.ds_range_max.setObjectName(_fromUtf8("ds_range_max"))
        self.gridLayout_6.addWidget(self.ds_range_max, 4, 4, 1, 1)
        self.field_component_label = QtGui.QLabel(self.group_box_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.field_component_label.setFont(font)
        self.field_component_label.setObjectName(_fromUtf8("field_component_label"))
        self.gridLayout_6.addWidget(self.field_component_label, 1, 0, 1, 2)
        self.to_label = QtGui.QLabel(self.group_box_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.to_label.setFont(font)
        self.to_label.setAlignment(QtCore.Qt.AlignCenter)
        self.to_label.setObjectName(_fromUtf8("to_label"))
        self.gridLayout_6.addWidget(self.to_label, 4, 3, 1, 1)
        self.file_label_3 = QtGui.QLabel(self.group_box_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.file_label_3.setFont(font)
        self.file_label_3.setObjectName(_fromUtf8("file_label_3"))
        self.gridLayout_6.addWidget(self.file_label_3, 0, 0, 1, 2)
        self.step_label = QtGui.QLabel(self.group_box_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.step_label.setFont(font)
        self.step_label.setAlignment(QtCore.Qt.AlignCenter)
        self.step_label.setObjectName(_fromUtf8("step_label"))
        self.gridLayout_6.addWidget(self.step_label, 4, 5, 1, 1)
        self.rb_norm_2 = QtGui.QRadioButton(self.group_box_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rb_norm_2.setFont(font)
        self.rb_norm_2.setChecked(True)
        self.rb_norm_2.setObjectName(_fromUtf8("rb_norm_2"))
        self.gridLayout_6.addWidget(self.rb_norm_2, 1, 3, 1, 2)
        self.ds_range_step = QtGui.QDoubleSpinBox(self.group_box_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ds_range_step.setFont(font)
        self.ds_range_step.setDecimals(1)
        self.ds_range_step.setMinimum(0.0)
        self.ds_range_step.setMaximum(5.0)
        self.ds_range_step.setSingleStep(0.1)
        self.ds_range_step.setProperty("value", 0.5)
        self.ds_range_step.setObjectName(_fromUtf8("ds_range_step"))
        self.gridLayout_6.addWidget(self.ds_range_step, 4, 6, 1, 1)
        self.cb_files_3 = QtGui.QComboBox(self.group_box_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_files_3.setFont(font)
        self.cb_files_3.setObjectName(_fromUtf8("cb_files_3"))
        self.gridLayout_6.addWidget(self.cb_files_3, 0, 3, 1, 4)
        self.rb_skew_2 = QtGui.QRadioButton(self.group_box_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rb_skew_2.setFont(font)
        self.rb_skew_2.setObjectName(_fromUtf8("rb_skew_2"))
        self.gridLayout_6.addWidget(self.rb_skew_2, 1, 5, 1, 2)
        self.range_label = QtGui.QLabel(self.group_box_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.range_label.setFont(font)
        self.range_label.setObjectName(_fromUtf8("range_label"))
        self.gridLayout_6.addWidget(self.range_label, 4, 0, 1, 2)
        self.group_box_15 = QtGui.QGroupBox(self.group_box_12)
        self.group_box_15.setGeometry(QtCore.QRect(840, 10, 271, 141))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.group_box_15.setFont(font)
        self.group_box_15.setObjectName(_fromUtf8("group_box_15"))
        self.spec_on_label = QtGui.QLabel(self.group_box_15)
        self.spec_on_label.setGeometry(QtCore.QRect(10, 40, 141, 31))
        self.spec_on_label.setObjectName(_fromUtf8("spec_on_label"))
        self.cb_spec_on = QtGui.QComboBox(self.group_box_15)
        self.cb_spec_on.setGeometry(QtCore.QRect(180, 40, 61, 31))
        self.cb_spec_on.setObjectName(_fromUtf8("cb_spec_on"))
        self.cb_spec_on.addItem(_fromUtf8(""))
        self.cb_spec_on.addItem(_fromUtf8(""))
        self.reference_radius_label = QtGui.QLabel(self.group_box_15)
        self.reference_radius_label.setGeometry(QtCore.QRect(10, 90, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.reference_radius_label.setFont(font)
        self.reference_radius_label.setObjectName(_fromUtf8("reference_radius_label"))
        self.ds_reference_radius = QtGui.QDoubleSpinBox(self.group_box_15)
        self.ds_reference_radius.setGeometry(QtCore.QRect(160, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ds_reference_radius.setFont(font)
        self.ds_reference_radius.setPrefix(_fromUtf8(""))
        self.ds_reference_radius.setDecimals(1)
        self.ds_reference_radius.setMinimum(0.0)
        self.ds_reference_radius.setMaximum(18.0)
        self.ds_reference_radius.setSingleStep(0.5)
        self.ds_reference_radius.setProperty("value", 18.0)
        self.ds_reference_radius.setObjectName(_fromUtf8("ds_reference_radius"))
        self.main_tab.addTab(self.residual, _fromUtf8(""))
        self.report = QtGui.QWidget()
        self.report.setObjectName(_fromUtf8("report"))
        self.group_box_18 = QtGui.QGroupBox(self.report)
        self.group_box_18.setGeometry(QtCore.QRect(10, 230, 411, 151))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.group_box_18.setFont(font)
        self.group_box_18.setObjectName(_fromUtf8("group_box_18"))
        self.gridLayout_8 = QtGui.QGridLayout(self.group_box_18)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.max_current_value = QtGui.QLineEdit(self.group_box_18)
        self.max_current_value.setObjectName(_fromUtf8("max_current_value"))
        self.gridLayout_8.addWidget(self.max_current_value, 2, 1, 1, 1)
        self.nr_turns_value = QtGui.QLineEdit(self.group_box_18)
        self.nr_turns_value.setObjectName(_fromUtf8("nr_turns_value"))
        self.gridLayout_8.addWidget(self.nr_turns_value, 3, 1, 1, 1)
        self.indutance_label = QtGui.QLabel(self.group_box_18)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.indutance_label.setFont(font)
        self.indutance_label.setObjectName(_fromUtf8("indutance_label"))
        self.gridLayout_8.addWidget(self.indutance_label, 0, 0, 1, 1)
        self.voltage_value = QtGui.QLineEdit(self.group_box_18)
        self.voltage_value.setObjectName(_fromUtf8("voltage_value"))
        self.gridLayout_8.addWidget(self.voltage_value, 1, 1, 1, 1)
        self.indutance_value = QtGui.QLineEdit(self.group_box_18)
        self.indutance_value.setObjectName(_fromUtf8("indutance_value"))
        self.gridLayout_8.addWidget(self.indutance_value, 0, 1, 1, 1)
        self.voltage_label = QtGui.QLabel(self.group_box_18)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.voltage_label.setFont(font)
        self.voltage_label.setObjectName(_fromUtf8("voltage_label"))
        self.gridLayout_8.addWidget(self.voltage_label, 1, 0, 1, 1)
        self.max_current_label = QtGui.QLabel(self.group_box_18)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.max_current_label.setFont(font)
        self.max_current_label.setObjectName(_fromUtf8("max_current_label"))
        self.gridLayout_8.addWidget(self.max_current_label, 2, 0, 1, 1)
        self.nr_turns_label = QtGui.QLabel(self.group_box_18)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.nr_turns_label.setFont(font)
        self.nr_turns_label.setObjectName(_fromUtf8("nr_turns_label"))
        self.gridLayout_8.addWidget(self.nr_turns_label, 3, 0, 1, 1)
        self.group_box_19 = QtGui.QGroupBox(self.report)
        self.group_box_19.setGeometry(QtCore.QRect(550, 30, 611, 761))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.group_box_19.setFont(font)
        self.group_box_19.setObjectName(_fromUtf8("group_box_19"))
        self.graphicsView = QtGui.QGraphicsView(self.group_box_19)
        self.graphicsView.setGeometry(QtCore.QRect(30, 40, 501, 691))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.bt_save_report = QtGui.QPushButton(self.report)
        self.bt_save_report.setGeometry(QtCore.QRect(250, 470, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bt_save_report.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("D:/ARQ/Lucas/Analise de dados BGL_(priscila)/imagens/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_save_report.setIcon(icon5)
        self.bt_save_report.setIconSize(QtCore.QSize(20, 20))
        self.bt_save_report.setObjectName(_fromUtf8("bt_save_report"))
        self.line_2 = QtGui.QFrame(self.report)
        self.line_2.setGeometry(QtCore.QRect(460, 0, 20, 811))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.group_box_16 = QtGui.QGroupBox(self.report)
        self.group_box_16.setGeometry(QtCore.QRect(10, 20, 441, 80))
        self.group_box_16.setObjectName(_fromUtf8("group_box_16"))
        self.file_label_4 = QtGui.QLabel(self.group_box_16)
        self.file_label_4.setGeometry(QtCore.QRect(16, 30, 111, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.file_label_4.setFont(font)
        self.file_label_4.setObjectName(_fromUtf8("file_label_4"))
        self.cb_files_4 = QtGui.QComboBox(self.group_box_16)
        self.cb_files_4.setGeometry(QtCore.QRect(150, 30, 251, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_files_4.setFont(font)
        self.cb_files_4.setObjectName(_fromUtf8("cb_files_4"))
        self.bt_preview = QtGui.QPushButton(self.report)
        self.bt_preview.setEnabled(False)
        self.bt_preview.setGeometry(QtCore.QRect(250, 410, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bt_preview.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("D:/ARQ/Lucas/Analise de dados BGL_(priscila)/imagens/Lupa2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_preview.setIcon(icon6)
        self.bt_preview.setIconSize(QtCore.QSize(25, 25))
        self.bt_preview.setObjectName(_fromUtf8("bt_preview"))
        self.group_box_17 = QtGui.QGroupBox(self.report)
        self.group_box_17.setGeometry(QtCore.QRect(10, 140, 441, 41))
        self.group_box_17.setObjectName(_fromUtf8("group_box_17"))
        self.cb_language = QtGui.QComboBox(self.group_box_17)
        self.cb_language.setGeometry(QtCore.QRect(150, 0, 251, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_language.setFont(font)
        self.cb_language.setObjectName(_fromUtf8("cb_language"))
        self.cb_language.addItem(_fromUtf8(""))
        self.cb_language.addItem(_fromUtf8(""))
        self.main_tab.addTab(self.report, _fromUtf8(""))
        self.wiki_graphs = QtGui.QWidget()
        self.wiki_graphs.setObjectName(_fromUtf8("wiki_graphs"))
        self.tab_wiki_graphs = QtGui.QTabWidget(self.wiki_graphs)
        self.tab_wiki_graphs.setEnabled(True)
        self.tab_wiki_graphs.setGeometry(QtCore.QRect(10, 100, 1181, 701))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tab_wiki_graphs.setFont(font)
        self.tab_wiki_graphs.setObjectName(_fromUtf8("tab_wiki_graphs"))
        self.roll_offset = QtGui.QWidget()
        self.roll_offset.setObjectName(_fromUtf8("roll_offset"))
        self.wt_roll_offset = matplotlibWidget(self.roll_offset)
        self.wt_roll_offset.setGeometry(QtCore.QRect(10, 10, 1161, 651))
        self.wt_roll_offset.setObjectName(_fromUtf8("wt_roll_offset"))
        self.tab_wiki_graphs.addTab(self.roll_offset, _fromUtf8(""))
        self.dipole = QtGui.QWidget()
        self.dipole.setObjectName(_fromUtf8("dipole"))
        self.wt_dipole = matplotlibWidget(self.dipole)
        self.wt_dipole.setGeometry(QtCore.QRect(10, 10, 1161, 651))
        self.wt_dipole.setObjectName(_fromUtf8("wt_dipole"))
        self.tab_wiki_graphs.addTab(self.dipole, _fromUtf8(""))
        self.quadrupole = QtGui.QWidget()
        self.quadrupole.setObjectName(_fromUtf8("quadrupole"))
        self.wt_quadrupole = matplotlibWidget(self.quadrupole)
        self.wt_quadrupole.setGeometry(QtCore.QRect(10, 10, 1161, 651))
        self.wt_quadrupole.setObjectName(_fromUtf8("wt_quadrupole"))
        self.tab_wiki_graphs.addTab(self.quadrupole, _fromUtf8(""))
        self.sextupole = QtGui.QWidget()
        self.sextupole.setObjectName(_fromUtf8("sextupole"))
        self.wt_sextupole = matplotlibWidget(self.sextupole)
        self.wt_sextupole.setGeometry(QtCore.QRect(10, 10, 1161, 651))
        self.wt_sextupole.setObjectName(_fromUtf8("wt_sextupole"))
        self.tab_wiki_graphs.addTab(self.sextupole, _fromUtf8(""))
        self.wiki_graphs_title = QtGui.QLineEdit(self.wiki_graphs)
        self.wiki_graphs_title.setGeometry(QtCore.QRect(100, 10, 811, 31))
        self.wiki_graphs_title.setText(_fromUtf8(""))
        self.wiki_graphs_title.setObjectName(_fromUtf8("wiki_graphs_title"))
        self.wiki_graphs_title_label = QtGui.QLabel(self.wiki_graphs)
        self.wiki_graphs_title_label.setGeometry(QtCore.QRect(10, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.wiki_graphs_title_label.setFont(font)
        self.wiki_graphs_title_label.setObjectName(_fromUtf8("wiki_graphs_title_label"))
        self.bt_plot_wiki_graphs = QtGui.QPushButton(self.wiki_graphs)
        self.bt_plot_wiki_graphs.setGeometry(QtCore.QRect(990, 30, 165, 61))
        self.bt_plot_wiki_graphs.setObjectName(_fromUtf8("bt_plot_wiki_graphs"))
        self.cb_wiki_graphs_label = QtGui.QComboBox(self.wiki_graphs)
        self.cb_wiki_graphs_label.setGeometry(QtCore.QRect(100, 50, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_wiki_graphs_label.setFont(font)
        self.cb_wiki_graphs_label.setObjectName(_fromUtf8("cb_wiki_graphs_label"))
        self.wiki_graphs_label_label = QtGui.QLabel(self.wiki_graphs)
        self.wiki_graphs_label_label.setGeometry(QtCore.QRect(10, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.wiki_graphs_label_label.setFont(font)
        self.wiki_graphs_label_label.setObjectName(_fromUtf8("wiki_graphs_label_label"))
        self.wiki_graphs_xlabel = QtGui.QLineEdit(self.wiki_graphs)
        self.wiki_graphs_xlabel.setGeometry(QtCore.QRect(560, 50, 351, 31))
        self.wiki_graphs_xlabel.setText(_fromUtf8(""))
        self.wiki_graphs_xlabel.setObjectName(_fromUtf8("wiki_graphs_xlabel"))
        self.wiki_graphs_xlabel_label = QtGui.QLabel(self.wiki_graphs)
        self.wiki_graphs_xlabel_label.setGeometry(QtCore.QRect(480, 50, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.wiki_graphs_xlabel_label.setFont(font)
        self.wiki_graphs_xlabel_label.setObjectName(_fromUtf8("wiki_graphs_xlabel_label"))
        self.main_tab.addTab(self.wiki_graphs, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.main_tab, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1234, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menu_open = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("../../.designer/backup/imagens/7547_128x128.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_open.setIcon(icon7)
        self.menu_open.setObjectName(_fromUtf8("menu_open"))
        self.menuFile.addAction(self.menu_open)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.main_tab.setCurrentIndex(0)
        self.cb_multipoles_2.setCurrentIndex(-1)
        self.cb_avg_1.setCurrentIndex(0)
        self.cb_multipoles_1.setCurrentIndex(-1)
        self.cb_files_1.setCurrentIndex(-1)
        self.cb_files_2.setCurrentIndex(-1)
        self.cb_avg_2.setCurrentIndex(0)
        self.cb_harmonic.setCurrentIndex(-1)
        self.cb_hyst_axis_label.setCurrentIndex(-1)
        self.tab_residual.setCurrentIndex(0)
        self.cb_avg_3.setCurrentIndex(0)
        self.cb_files_3.setCurrentIndex(-1)
        self.cb_spec_on.setCurrentIndex(0)
        self.cb_files_4.setCurrentIndex(-1)
        self.cb_language.setCurrentIndex(0)
        self.tab_wiki_graphs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.group_box_6.setTitle(_translate("MainWindow", "Files Directory:", None))
        self.bt_upload_files.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enviar arquivos para lista de dados selecionados.</p></body></html>", None))
        self.group_box_2.setTitle(_translate("MainWindow", "Loaded files", None))
        self.group_box_3.setTitle(_translate("MainWindow", "Number", None))
        self.input_count.setText(_translate("MainWindow", "0", None))
        self.input_count_label.setText(_translate("MainWindow", "Total:", None))
        item = self.input_list.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Arquivo", None))
        self.bt_clear_input_list.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Limpar tabela.</span></p></body></html>", None))
        self.bt_clear_input_list.setText(_translate("MainWindow", "Clean", None))
        self.data_analysis_label.setText(_translate("MainWindow", "Rotating Coil Data Analysis", None))
        self.group_box_4.setTitle(_translate("MainWindow", "Files selected for analysis", None))
        self.group_box_5.setTitle(_translate("MainWindow", "Number", None))
        self.output_count.setText(_translate("MainWindow", "0", None))
        self.output_count_label.setText(_translate("MainWindow", "Selected:", None))
        self.bt_clear_output_list.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Limpar tabela.</span></p></body></html>", None))
        self.bt_clear_output_list.setText(_translate("MainWindow", "Clean", None))
        item = self.output_list.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Arquivo", None))
        self.bt_remove_files.setToolTip(_translate("MainWindow", "<html><head/><body><p>Excluir arquivos da lista de dados selecionados.</p></body></html>", None))
        self.bt_data_analysis.setText(_translate("MainWindow", "Analyze", None))
        self.bt_open_file.setText(_translate("MainWindow", "Load Files", None))
        self.main_tab.setTabText(self.main_tab.indexOf(self.configuration), _translate("MainWindow", "Configuration", None))
        self.group_box_9.setTitle(_translate("MainWindow", "Multipoles - All Files", None))
        self.column_label_2.setText(_translate("MainWindow", "Column:", None))
        self.avg_label_1.setText(_translate("MainWindow", "Mean:", None))
        self.bt_table_2.setText(_translate("MainWindow", "...", None))
        self.cb_avg_1.setItemText(0, _translate("MainWindow", "ON", None))
        self.cb_avg_1.setItemText(1, _translate("MainWindow", "OFF", None))
        self.bt_plot_multipoles_all.setText(_translate("MainWindow", "Plot", None))
        self.group_box_8.setTitle(_translate("MainWindow", "Multipoles - One File", None))
        self.file_label_1.setText(_translate("MainWindow", "Current (A):", None))
        self.column_label_1.setText(_translate("MainWindow", "Column:", None))
        self.bt_table_1.setText(_translate("MainWindow", "...", None))
        self.bt_plot_multipoles.setText(_translate("MainWindow", "Plot", None))
        self.group_box_11.setTitle(_translate("MainWindow", "Raw Data", None))
        self.file_label_2.setText(_translate("MainWindow", "Current (A):", None))
        self.bt_plot_raw_data.setText(_translate("MainWindow", "Plot (One File)", None))
        self.avg_label_2.setText(_translate("MainWindow", "Mean:", None))
        self.cb_avg_2.setItemText(0, _translate("MainWindow", "ON", None))
        self.cb_avg_2.setItemText(1, _translate("MainWindow", "OFF", None))
        self.bt_plot_raw_data_all.setText(_translate("MainWindow", "Plot (All Files) ", None))
        self.bt_table_4.setText(_translate("MainWindow", "...", None))
        self.group_box_10.setTitle(_translate("MainWindow", "Multipole vs", None))
        self.rb_norm.setText(_translate("MainWindow", "Normal", None))
        self.rb_skew.setText(_translate("MainWindow", "Skew", None))
        self.bt_table_3.setText(_translate("MainWindow", "...", None))
        self.bt_plot_hysteresis.setText(_translate("MainWindow", "Plot", None))
        self.harmonic_label.setText(_translate("MainWindow", "Harmonic:", None))
        self.hyst_axis_label_label.setText(_translate("MainWindow", "Files Label:", None))
        self.main_tab.setTabText(self.main_tab.indexOf(self.multipoles), _translate("MainWindow", "Multipoles and Raw Data", None))
        self.tab_residual.setTabText(self.tab_residual.indexOf(self.residual_field), _translate("MainWindow", "Residual Field", None))
        self.tab_residual.setTabText(self.tab_residual.indexOf(self.residual_multipoles), _translate("MainWindow", "Residual Multipoles", None))
        item = self.table_one_file.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Center Offset X [μm]", None))
        item = self.table_one_file.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Center Offset Y [μm]", None))
        item = self.table_one_file.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Roll [mrad]", None))
        item = self.table_avg.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Center Offset X [μm]", None))
        item = self.table_avg.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Center Offset Y [μm]", None))
        item = self.table_avg.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Roll [mrad]", None))
        item = self.table_all_files.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Center Offset X [μm]", None))
        item = self.table_all_files.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Center Offset Y [μm]", None))
        item = self.table_all_files.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Roll [mrad]", None))
        self.selected_file_label.setText(_translate("MainWindow", "Selected File:", None))
        self.mean_label.setText(_translate("MainWindow", "Mean:", None))
        self.all_files_label.setText(_translate("MainWindow", "All files:", None))
        self.tab_residual.setTabText(self.tab_residual.indexOf(self.residual_tables), _translate("MainWindow", "Roll and Center Offset", None))
        self.avg_label_3.setText(_translate("MainWindow", "Mean", None))
        self.bt_plot_residual_field_all.setText(_translate("MainWindow", "Plot (All files)", None))
        self.cb_avg_3.setItemText(0, _translate("MainWindow", "ON", None))
        self.cb_avg_3.setItemText(1, _translate("MainWindow", "OFF", None))
        self.bt_table_5.setText(_translate("MainWindow", "...", None))
        self.bt_plot_residual_field.setText(_translate("MainWindow", "Plot (One file)", None))
        self.group_box_13.setTitle(_translate("MainWindow", "Normalized Residual Multipoles", None))
        self.field_component_label.setText(_translate("MainWindow", "Field Component: ", None))
        self.to_label.setText(_translate("MainWindow", "to", None))
        self.file_label_3.setText(_translate("MainWindow", "Current (A):", None))
        self.step_label.setText(_translate("MainWindow", "step: ", None))
        self.rb_norm_2.setText(_translate("MainWindow", "Normal", None))
        self.rb_skew_2.setText(_translate("MainWindow", "Skew", None))
        self.range_label.setText(_translate("MainWindow", "Range [mm]: ", None))
        self.group_box_15.setTitle(_translate("MainWindow", "Multipole errors specifications", None))
        self.spec_on_label.setText(_translate("MainWindow", "Add to graph:", None))
        self.cb_spec_on.setItemText(0, _translate("MainWindow", "ON", None))
        self.cb_spec_on.setItemText(1, _translate("MainWindow", "OFF", None))
        self.reference_radius_label.setText(_translate("MainWindow", "@Reference radius:\n"
"              [mm]", None))
        self.main_tab.setTabText(self.main_tab.indexOf(self.residual), _translate("MainWindow", "Residual Multipoles", None))
        self.group_box_18.setTitle(_translate("MainWindow", "Electric Parameters", None))
        self.indutance_label.setText(_translate("MainWindow", "Indutance [mH]:", None))
        self.voltage_label.setText(_translate("MainWindow", "Voltage [V]:", None))
        self.max_current_label.setText(_translate("MainWindow", "Main Coil Maximum Current [A]:   ", None))
        self.nr_turns_label.setText(_translate("MainWindow", "Main Coil Number of Turns:", None))
        self.group_box_19.setTitle(_translate("MainWindow", "Preview", None))
        self.bt_save_report.setText(_translate("MainWindow", "Save Report", None))
        self.group_box_16.setTitle(_translate("MainWindow", "Select file", None))
        self.file_label_4.setText(_translate("MainWindow", "Current (A):", None))
        self.bt_preview.setText(_translate("MainWindow", "Preview", None))
        self.group_box_17.setTitle(_translate("MainWindow", "Select language", None))
        self.cb_language.setItemText(0, _translate("MainWindow", "English", None))
        self.cb_language.setItemText(1, _translate("MainWindow", "Portuguese", None))
        self.main_tab.setTabText(self.main_tab.indexOf(self.report), _translate("MainWindow", "Report", None))
        self.tab_wiki_graphs.setTabText(self.tab_wiki_graphs.indexOf(self.roll_offset), _translate("MainWindow", "Roll and Center Offset", None))
        self.tab_wiki_graphs.setTabText(self.tab_wiki_graphs.indexOf(self.dipole), _translate("MainWindow", "Integrated Dipole", None))
        self.tab_wiki_graphs.setTabText(self.tab_wiki_graphs.indexOf(self.quadrupole), _translate("MainWindow", "Integrated Quadrupole", None))
        self.tab_wiki_graphs.setTabText(self.tab_wiki_graphs.indexOf(self.sextupole), _translate("MainWindow", "Integrated Sextupole", None))
        self.wiki_graphs_title_label.setText(_translate("MainWindow", "Title:", None))
        self.bt_plot_wiki_graphs.setText(_translate("MainWindow", "Plot", None))
        self.wiki_graphs_label_label.setText(_translate("MainWindow", "X Ticks:", None))
        self.wiki_graphs_xlabel_label.setText(_translate("MainWindow", "X Label:", None))
        self.main_tab.setTabText(self.main_tab.indexOf(self.wiki_graphs), _translate("MainWindow", "Wiki Graphics", None))
        self.menuFile.setTitle(_translate("MainWindow", "Arquivo", None))
        self.menu_open.setText(_translate("MainWindow", "Abrir Arquivos", None))

from plot_widget import matplotlibWidget
import resources_rc
